import type { OxlintConfig } from "oxlint";
import fs from "node:fs/promises";
import path from "node:path";
import migrate from "@oxlint/migrate";
import { comments } from "../../src/configs/comments";
import { ignores } from "../../src/configs/ignores";
import { imports } from "../../src/configs/imports";
import { javascript } from "../../src/configs/javascript";
import { jsdoc } from "../../src/configs/jsdoc";
import { jsx } from "../../src/configs/jsx";
import { nextjs } from "../../src/configs/nextjs";
import { node } from "../../src/configs/node";
import { react } from "../../src/configs/react";
import { test } from "../../src/configs/test";
import { typescript } from "../../src/configs/typescript";
import { unicorn } from "../../src/configs/unicorn";
import { vue } from "../../src/configs/vue";
import {
  GLOB_JSX,
  GLOB_SRC,
  GLOB_TESTS,
  GLOB_TS,
  GLOB_TSX,
  GLOB_VUE,
} from "../../src/globs";
import type { TypedFlatConfigItem } from "../../src/types";
import {
  countConfiguredRules,
  mergeOxlintConfigs,
  normalizeOxlintConfig,
  prepareMigrationSource,
  restoreMigrationScopes,
  sortGeneratedValue,
  translateOxlintGlobs,
} from "./normalize";
import type { SkippedRulesByCategory } from "./reporter";
import { MigrationReporter } from "./reporter";

const generatedDirectory = "src/generated/oxlint";
const banner =
  "// This file is generated by scripts/generate-oxlint.ts. Do not edit it manually.\n";

interface GeneratedFragmentData {
  config: OxlintConfig;
  overrideTarget?: {
    excludeFiles?: Array<string>;
    files: Array<string>;
  };
}

interface GenerateFragmentOptions {
  defaultRuleFiles: Array<string>;
  overrideTarget?: GeneratedFragmentData["overrideTarget"];
  source: Array<TypedFlatConfigItem>;
  sourceName: string;
  typeAware?: boolean;
}

interface MigrateSourceOptions {
  defaultRuleFiles?: Array<string>;
  stripBaseline?: boolean;
  typeAware?: boolean;
}

interface VariantCompatibility {
  migratedRuleCount: number;
  skippedRules: SkippedRulesByCategory;
  sources: Array<string>;
  status: "partial" | "supported";
  warnings: Array<string>;
}

interface CompatibilityReportData {
  generation: {
    jsPlugins: false;
    typeAware: "per-variant";
    withNursery: false;
  };
  limitations: Array<{
    classification:
      | "generated-adaptation"
      | "intentional-v1"
      | "runtime-requirement"
      | "upstream";
    description: string;
    id: string;
  }>;
  schemaVersion: 1;
  variants: Record<string, VariantCompatibility>;
  versions: {
    migrate: string;
    oxlint: string;
  };
}

interface GeneratedData {
  fragments: {
    base: {
      default: OxlintConfig;
      editor: OxlintConfig;
    };
    unicorn: {
      allRecommended: GeneratedFragmentData;
      selected: GeneratedFragmentData;
    };
    jsx: GeneratedFragmentData;
    typescript: {
      app: {
        standard: GeneratedFragmentData;
        typeAware: GeneratedFragmentData;
      };
      lib: {
        standard: GeneratedFragmentData;
        typeAware: GeneratedFragmentData;
      };
    };
    test: {
      default: GeneratedFragmentData;
      editor: GeneratedFragmentData;
    };
    vue: {
      javascript: GeneratedFragmentData;
      typescript: GeneratedFragmentData;
    };
    react: {
      standard: GeneratedFragmentData;
      typeAware: GeneratedFragmentData;
    };
    nextjs: GeneratedFragmentData;
    jsdoc: GeneratedFragmentData;
  };
  report: CompatibilityReportData;
}

export interface OxlintArtifactDiff {
  changed: Array<string>;
  missing: Array<string>;
  unexpected: Array<string>;
}

type RenderedArtifacts = ReadonlyMap<string, string>;

async function migrateSource(
  source: Array<TypedFlatConfigItem>,
  reporter: MigrationReporter,
  options: MigrateSourceOptions = {},
): Promise<OxlintConfig> {
  const {
    defaultRuleFiles,
    stripBaseline = true,
    typeAware = false,
  } = options;
  const prepared = prepareMigrationSource(source, defaultRuleFiles);
  const migrated = await migrate(prepared.configs, undefined, {
    jsPlugins: false,
    reporter,
    typeAware,
    withNursery: false,
  });
  const restored = restoreMigrationScopes(migrated, prepared.scopes);
  return normalizeOxlintConfig(restored, stripBaseline);
}

function variantCompatibility(
  config: OxlintConfig,
  reporter: MigrationReporter,
  sources: Array<string>,
): VariantCompatibility {
  const skippedRules = reporter.getSkippedRulesByCategory();
  const isPartial = Object.values(skippedRules).some(
    (rules) => rules.length > 0,
  );
  return {
    migratedRuleCount: countConfiguredRules(config),
    skippedRules,
    sources: [...sources],
    status: isPartial ? "partial" : "supported",
    warnings: reporter.getWarnings(),
  };
}

async function generateBase(
  isInEditor: boolean,
): Promise<{ config: OxlintConfig; compatibility: VariantCompatibility }> {
  const reporter = new MigrationReporter();
  const sourceUnits = [
    ["ignores", await ignores()],
    ["javascript", await javascript({ isInEditor })],
    ["comments", await comments()],
    ["node", await node()],
    ["imports", await imports({ stylistic: false })],
  ] as const;
  const migratedUnits: Array<OxlintConfig> = [];

  for (const [, source] of sourceUnits) {
    migratedUnits.push(
      await migrateSource(source, reporter, { stripBaseline: false }),
    );
  }

  const config = mergeOxlintConfigs(migratedUnits);
  return {
    compatibility: variantCompatibility(
      config,
      reporter,
      sourceUnits.map(([name]) => name),
    ),
    config,
  };
}

async function generateFragment(
  options: GenerateFragmentOptions,
): Promise<{
  compatibility: VariantCompatibility;
  fragment: GeneratedFragmentData;
}> {
  const {
    defaultRuleFiles,
    source,
    sourceName,
    typeAware = false,
  } = options;
  const overrideTarget = options.overrideTarget ?? { files: defaultRuleFiles };
  const reporter = new MigrationReporter();
  const config = await migrateSource(source, reporter, {
    defaultRuleFiles,
    typeAware,
  });

  return {
    compatibility: variantCompatibility(config, reporter, [sourceName]),
    fragment: {
      config,
      overrideTarget: {
        ...overrideTarget,
        ...(overrideTarget?.excludeFiles == null
          ? {}
          : {
              excludeFiles: translateOxlintGlobs(
                overrideTarget.excludeFiles,
              ),
            }),
        files: translateOxlintGlobs(
          overrideTarget?.files ?? defaultRuleFiles,
        ),
      },
    },
  };
}

async function readPackageVersion(url: URL): Promise<string> {
  const packageJson = JSON.parse(await fs.readFile(url, "utf8")) as {
    version?: unknown;
  };
  if (typeof packageJson.version !== "string") {
    throw new TypeError(`Package at ${url.pathname} has no string version`);
  }
  return packageJson.version;
}

function compatibilityLimitations(): CompatibilityReportData["limitations"] {
  return [
    {
      classification: "intentional-v1",
      description:
        "Only rules implemented natively by Oxlint are emitted; JavaScript plugin fallbacks are withheld in v1.",
      id: "native-only-v1",
    },
    {
      classification: "upstream",
      description:
        "Rules listed as skipped remain governed by @oxlint/migrate and Oxlint support in the pinned versions.",
      id: "upstream-rule-coverage",
    },
    {
      classification: "generated-adaptation",
      description:
        "ESLint override ignores are restored as Oxlint excludeFiles because the migrator does not preserve them.",
      id: "override-ignore-restoration",
    },
    {
      classification: "generated-adaptation",
      description:
        "Rule-bearing root items in optional integrations are scoped to that integration's default files.",
      id: "integration-rule-scoping",
    },
    {
      classification: "intentional-v1",
      description:
        "React variants are generated with package detection disabled, so their migrated react/only-export-components options are frozen and do not automatically adapt to installed Next.js, Vite, or Remix packages; the separately enabled Next.js fragment still applies its own rule.",
      id: "react-refresh-environment-detection",
    },
    {
      classification: "runtime-requirement",
      description:
        "Type-aware variants require oxlint-tsgolint at runtime and set options.typeAware.",
      id: "type-aware-runtime",
    },
  ];
}

async function generateData(): Promise<GeneratedData> {
  const variants: Record<string, VariantCompatibility> = {};

  const baseDefault = await generateBase(false);
  variants["base.default"] = baseDefault.compatibility;
  const baseEditor = await generateBase(true);
  variants["base.editor"] = baseEditor.compatibility;

  const unicornAllRecommended = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await unicorn({ allRecommended: true }),
    sourceName: "unicorn",
  });
  variants["unicorn.allRecommended"] =
    unicornAllRecommended.compatibility;
  const unicornSelected = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await unicorn({ allRecommended: false }),
    sourceName: "unicorn",
  });
  variants["unicorn.selected"] = unicornSelected.compatibility;

  const jsxFragment = await generateFragment({
    defaultRuleFiles: [GLOB_JSX, GLOB_TSX],
    source: await jsx(),
    sourceName: "jsx",
  });
  variants.jsx = jsxFragment.compatibility;

  const typescriptAppStandard = await generateFragment({
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    source: await typescript({ erasableOnly: true, type: "app" }),
    sourceName: "typescript",
  });
  variants["typescript.app.standard"] =
    typescriptAppStandard.compatibility;
  const typescriptAppTypeAware = await generateFragment({
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    source: await typescript({
      erasableOnly: true,
      tsconfigPath: "tsconfig.json",
      type: "app",
    }),
    sourceName: "typescript",
    typeAware: true,
  });
  variants["typescript.app.typeAware"] =
    typescriptAppTypeAware.compatibility;
  const typescriptLibStandard = await generateFragment({
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    source: await typescript({ erasableOnly: true, type: "lib" }),
    sourceName: "typescript",
  });
  variants["typescript.lib.standard"] =
    typescriptLibStandard.compatibility;
  const typescriptLibTypeAware = await generateFragment({
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    source: await typescript({
      erasableOnly: true,
      tsconfigPath: "tsconfig.json",
      type: "lib",
    }),
    sourceName: "typescript",
    typeAware: true,
  });
  variants["typescript.lib.typeAware"] =
    typescriptLibTypeAware.compatibility;

  const testDefault = await generateFragment({
    defaultRuleFiles: GLOB_TESTS,
    source: await test({ isInEditor: false }),
    sourceName: "test",
  });
  variants["test.default"] = testDefault.compatibility;
  const testEditor = await generateFragment({
    defaultRuleFiles: GLOB_TESTS,
    source: await test({ isInEditor: true }),
    sourceName: "test",
  });
  variants["test.editor"] = testEditor.compatibility;

  const vueJavaScript = await generateFragment({
    defaultRuleFiles: [GLOB_VUE],
    source: await vue({
      a11y: false,
      sfcBlocks: false,
      stylistic: false,
      typescript: false,
    }),
    sourceName: "vue",
  });
  variants["vue.javascript"] = vueJavaScript.compatibility;
  const vueTypeScript = await generateFragment({
    defaultRuleFiles: [GLOB_VUE],
    source: await vue({
      a11y: false,
      sfcBlocks: false,
      stylistic: false,
      typescript: true,
    }),
    sourceName: "vue",
  });
  variants["vue.typescript"] = vueTypeScript.compatibility;

  const neutralReactEnvironment = { hasPackage: () => false };
  const reactStandard = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await react({}, neutralReactEnvironment),
    sourceName: "react",
  });
  variants["react.standard"] = reactStandard.compatibility;
  const reactTypeAware = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await react(
      { tsconfigPath: "tsconfig.json" },
      neutralReactEnvironment,
    ),
    sourceName: "react",
    typeAware: true,
  });
  variants["react.typeAware"] = reactTypeAware.compatibility;

  const nextjsFragment = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await nextjs(),
    sourceName: "nextjs",
  });
  variants.nextjs = nextjsFragment.compatibility;
  const jsdocFragment = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    source: await jsdoc({ stylistic: false }),
    sourceName: "jsdoc",
  });
  variants.jsdoc = jsdocFragment.compatibility;

  const [migrateVersion, oxlintVersion] = await Promise.all([
    readPackageVersion(
      new URL("../../node_modules/@oxlint/migrate/package.json", import.meta.url),
    ),
    readPackageVersion(
      new URL("../../node_modules/oxlint/package.json", import.meta.url),
    ),
  ]);

  return {
    fragments: {
      base: {
        default: baseDefault.config,
        editor: baseEditor.config,
      },
      unicorn: {
        allRecommended: unicornAllRecommended.fragment,
        selected: unicornSelected.fragment,
      },
      jsx: jsxFragment.fragment,
      typescript: {
        app: {
          standard: typescriptAppStandard.fragment,
          typeAware: typescriptAppTypeAware.fragment,
        },
        lib: {
          standard: typescriptLibStandard.fragment,
          typeAware: typescriptLibTypeAware.fragment,
        },
      },
      test: {
        default: testDefault.fragment,
        editor: testEditor.fragment,
      },
      vue: {
        javascript: vueJavaScript.fragment,
        typescript: vueTypeScript.fragment,
      },
      react: {
        standard: reactStandard.fragment,
        typeAware: reactTypeAware.fragment,
      },
      nextjs: nextjsFragment.fragment,
      jsdoc: jsdocFragment.fragment,
    },
    report: {
      generation: {
        jsPlugins: false,
        typeAware: "per-variant",
        withNursery: false,
      },
      limitations: compatibilityLimitations(),
      schemaVersion: 1,
      variants,
      versions: {
        migrate: migrateVersion,
        oxlint: oxlintVersion,
      },
    },
  };
}

function renderValue(value: unknown): string {
  return JSON.stringify(sortGeneratedValue(value), null, 2);
}

function renderFragments(fragments: GeneratedData["fragments"]): string {
  return `${banner}import type { OxlintConfig } from "oxlint";

export interface GeneratedFragment {
  config: OxlintConfig;
  overrideTarget?: {
    excludeFiles?: Array<string>;
    files: Array<string>;
  };
}

export interface GeneratedOxlintFragments {
  base: { default: OxlintConfig; editor: OxlintConfig };
  unicorn: { allRecommended: GeneratedFragment; selected: GeneratedFragment };
  jsx: GeneratedFragment;
  typescript: {
    app: { standard: GeneratedFragment; typeAware: GeneratedFragment };
    lib: { standard: GeneratedFragment; typeAware: GeneratedFragment };
  };
  test: { default: GeneratedFragment; editor: GeneratedFragment };
  vue: { javascript: GeneratedFragment; typescript: GeneratedFragment };
  react: { standard: GeneratedFragment; typeAware: GeneratedFragment };
  nextjs: GeneratedFragment;
  jsdoc: GeneratedFragment;
}

export const generatedOxlintFragments: GeneratedOxlintFragments = ${renderValue(
    fragments,
  )};
`;
}

function renderCompatibilityReport(report: CompatibilityReportData): string {
  return `${banner}export type OxlintLimitationClassification =
  | "generated-adaptation"
  | "intentional-v1"
  | "runtime-requirement"
  | "upstream";

export type OxlintSkippedRuleCategory =
  | "js-plugins"
  | "not-implemented"
  | "nursery"
  | "type-aware"
  | "unsupported";

export interface OxlintVariantCompatibility {
  migratedRuleCount: number;
  skippedRules: Record<OxlintSkippedRuleCategory, Array<string>>;
  sources: Array<string>;
  status: "partial" | "supported";
  warnings: Array<string>;
}

export interface OxlintCompatibilityReport {
  generation: {
    jsPlugins: false;
    typeAware: "per-variant";
    withNursery: false;
  };
  limitations: Array<{
    classification: OxlintLimitationClassification;
    description: string;
    id: string;
  }>;
  schemaVersion: 1;
  variants: Record<string, OxlintVariantCompatibility>;
  versions: { migrate: string; oxlint: string };
}

export const oxlintCompatibilityReport: OxlintCompatibilityReport = ${renderValue(
    report,
  )};
`;
}

export async function renderOxlintArtifacts(): Promise<Map<string, string>> {
  const data = await generateData();
  return new Map([
    [
      `${generatedDirectory}/compatibility-report.ts`,
      renderCompatibilityReport(data.report),
    ],
    [`${generatedDirectory}/fragments.ts`, renderFragments(data.fragments)],
    [
      `${generatedDirectory}/index.ts`,
      `${banner}export * from "./compatibility-report";\nexport * from "./fragments";\n`,
    ],
  ]);
}

async function listFiles(directory: string): Promise<Array<string>> {
  let entries;
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }

  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      return entry.isDirectory() ? await listFiles(entryPath) : [entryPath];
    }),
  );
  return files.flat().toSorted((left, right) => left.localeCompare(right));
}

export function normalizeOxlintArtifactPath(relativePath: string): string {
  return relativePath.replaceAll(path.win32.sep, path.posix.sep);
}

export async function diffOxlintArtifacts(
  root: string,
  rendered: RenderedArtifacts,
): Promise<OxlintArtifactDiff> {
  const expectedFiles = [...rendered.keys()].toSorted((left, right) =>
    left.localeCompare(right),
  );
  const changed: Array<string> = [];
  const missing: Array<string> = [];

  for (const relativePath of expectedFiles) {
    try {
      const actual = await fs.readFile(path.join(root, relativePath), "utf8");
      if (actual !== rendered.get(relativePath)) changed.push(relativePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        missing.push(relativePath);
        continue;
      }
      throw error;
    }
  }

  const actualFiles = await listFiles(path.join(root, generatedDirectory));
  const expected = new Set(expectedFiles);
  const unexpected = actualFiles
    .map((file) => normalizeOxlintArtifactPath(path.relative(root, file)))
    .filter((file) => !expected.has(file))
    .toSorted((left, right) => left.localeCompare(right));

  return { changed, missing, unexpected };
}

export async function writeOxlintArtifacts(
  root: string,
  rendered: RenderedArtifacts,
): Promise<void> {
  const diff = await diffOxlintArtifacts(root, rendered);
  await Promise.all(
    diff.unexpected.map((relativePath) =>
      fs.rm(path.join(root, relativePath), { force: true }),
    ),
  );

  for (const [relativePath, contents] of rendered) {
    const filePath = path.join(root, relativePath);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, contents);
  }
}

export function hasOxlintArtifactDiff(diff: OxlintArtifactDiff): boolean {
  return (
    diff.changed.length > 0 ||
    diff.missing.length > 0 ||
    diff.unexpected.length > 0
  );
}

export function formatOxlintArtifactDiff(diff: OxlintArtifactDiff): string {
  const lines = ["Generated Oxlint artifacts are out of date."];
  for (const file of diff.changed) lines.push(`  changed: ${file}`);
  for (const file of diff.missing) lines.push(`  missing: ${file}`);
  for (const file of diff.unexpected) lines.push(`  unexpected: ${file}`);
  lines.push("Run `pnpm generate:oxlint` and commit the result.");
  return lines.join("\n");
}
