import migrate from "@oxlint/migrate";
import fs from "node:fs/promises";
import path from "node:path";
import type { OxlintConfig } from "oxlint";
import { angular } from "../../src/configs/angular";
import { command } from "../../src/configs/command";
import { comments } from "../../src/configs/comments";
import { defaultImportName } from "../../src/configs/default-import-name";
import { disables } from "../../src/configs/disables";
import { e18e } from "../../src/configs/e18e";
import { i18n } from "../../src/configs/i18n";
import { ignores } from "../../src/configs/ignores";
import { imports } from "../../src/configs/imports";
import { javascript } from "../../src/configs/javascript";
import { jsdoc } from "../../src/configs/jsdoc";
import { jsx } from "../../src/configs/jsx";
import { nextjs } from "../../src/configs/nextjs";
import { node } from "../../src/configs/node";
import { perfectionist } from "../../src/configs/perfectionist";
import { prettier } from "../../src/configs/prettier";
import { query } from "../../src/configs/query";
import { react } from "../../src/configs/react";
import { regexp } from "../../src/configs/regexp";
import { security } from "../../src/configs/security";
import { solid } from "../../src/configs/solid";
import { storybook } from "../../src/configs/storybook";
import { stylistic } from "../../src/configs/stylistic";
import { tailwindcss } from "../../src/configs/tailwindcss";
import { test } from "../../src/configs/test";
import { tsdoc } from "../../src/configs/tsdoc";
import { typescript } from "../../src/configs/typescript";
import { unicorn } from "../../src/configs/unicorn";
import { unocss } from "../../src/configs/unocss";
import { vue } from "../../src/configs/vue";
import { zod } from "../../src/configs/zod";
import {
  GLOB_JSX,
  GLOB_SRC,
  GLOB_TESTS,
  GLOB_TS,
  GLOB_TSX,
  GLOB_VUE,
} from "../../src/globs";
import {
  typeAwareExcludesPlaceholder,
  typeAwareFilesPlaceholder,
} from "../../src/oxlint/type-aware-scope";
import type { TypedFlatConfigItem } from "../../src/types";
import {
  countConfiguredRules,
  markDisabledRulesForMigration,
  mergeOxlintConfigs,
  normalizeOxlintConfig,
  prepareMigrationSource,
  restoreDisabledRulesAfterMigration,
  restoreMigrationScopes,
  sortGeneratedValue,
  translateOxlintGlobs,
} from "./normalize";
import type { SkippedRulesByCategory } from "./reporter";
import { MigrationReporter } from "./reporter";

const generatedDirectory = "src/generated/oxlint";
const banner =
  "// This file is generated by scripts/generate-oxlint.ts. Do not edit it manually.\n";
const executableSolidConfigNames = new Set([
  "nirtamir2/solid/typescript-disables",
]);
const solidReactRulesOffConfigName = "nirtamir2/solid/react-rules-off";
const antfuFallback = {
  pluginName: "antfu",
  sourceRulePrefix: "antfu",
  specifier: "eslint-plugin-antfu",
  targetRulePrefix: "antfu",
} satisfies AliasedFallback;

interface GeneratedFragmentData {
  config: OxlintConfig;
  overrideTarget?: {
    excludeFiles?: Array<string>;
    files: Array<string>;
  };
}

interface GenerateFragmentOptions {
  adaptations?: Array<string>;
  aliasedFallbacks?: Array<AliasedFallback>;
  defaultRuleFiles: Array<string>;
  jsPlugins?: boolean;
  overrideTarget?: GeneratedFragmentData["overrideTarget"];
  source: Array<TypedFlatConfigItem>;
  sourceName: string;
  transform?: (config: OxlintConfig) => OxlintConfig;
  typeAware?: boolean;
}

interface AliasedFallback {
  categories?: Array<"js-plugins" | "not-implemented" | "unsupported">;
  includeConfiguredRules?: boolean;
  pluginName: string;
  sourceRulePrefix: string;
  specifier: string;
  targetRulePrefix: string;
}

interface MigrateSourceOptions {
  defaultRuleFiles?: Array<string>;
  jsPlugins?: boolean;
  preserveDisabledRules?: boolean;
  stripBaseline?: boolean;
  typeAware?: boolean;
}

interface RootSourceUnitOptions {
  jsPlugins?: boolean;
  preserveDisabledRules?: boolean;
}

type RootSourceUnit = readonly [
  string,
  Array<TypedFlatConfigItem>,
  RootSourceUnitOptions?,
];

interface VariantCompatibility {
  adaptations: Array<string>;
  jsPlugins: boolean;
  migratedRuleCount: number;
  skippedRules: SkippedRulesByCategory;
  sources: Array<string>;
  status: "partial" | "supported";
  withNursery: boolean;
  warnings: Array<string>;
}

interface VariantCompatibilityOptions {
  adaptations?: Array<string>;
  jsPlugins: boolean;
  recoveredRules?: ReadonlySet<string>;
  sources: Array<string>;
}

interface AliasedFallbackOptions {
  defaultRuleFiles?: Array<string>;
  fallback: AliasedFallback;
}

interface CompatibilityReportData {
  generation: {
    jsPlugins: "per-variant";
    typeAware: "per-variant";
    withNursery: true;
  };
  limitations: Array<{
    classification:
      | "generated-adaptation"
      | "intentional-v1"
      | "runtime-requirement"
      | "upstream";
    description: string;
    id: string;
  }>;
  schemaVersion: 3;
  variants: Record<string, VariantCompatibility>;
  versions: {
    migrate: string;
    oxlint: string;
  };
}

interface GeneratedData {
  fragments: {
    base: {
      default: OxlintConfig;
      editor: OxlintConfig;
      suffix: OxlintConfig;
    };
    command: OxlintConfig;
    e18e: {
      app: { default: OxlintConfig; editor: OxlintConfig };
      base: { app: OxlintConfig; lib: OxlintConfig };
      lib: { default: OxlintConfig; editor: OxlintConfig };
      modernization: OxlintConfig;
      moduleReplacements: OxlintConfig;
      performanceImprovements: { app: OxlintConfig; lib: OxlintConfig };
    };
    regexp: { error: OxlintConfig; warn: OxlintConfig };
    integrations: {
      angular: GeneratedFragmentData;
      i18n: GeneratedFragmentData;
      importsStylistic: OxlintConfig;
      perfectionist: OxlintConfig;
      query: OxlintConfig;
      security: OxlintConfig;
      solid: {
        javascript: GeneratedFragmentData;
        reactDisables: GeneratedFragmentData;
        typescript: GeneratedFragmentData;
      };
      storybook: OxlintConfig;
      stylistic: {
        default: OxlintConfig;
        lessOpinionated: OxlintConfig;
        lessOpinionatedNoJsx: OxlintConfig;
        noJsx: OxlintConfig;
      };
      stylisticCustomizations: {
        braceStyle: { allman: OxlintConfig; oneTrueBrace: OxlintConfig };
        experimental: OxlintConfig;
        indent: { numberTemplate: OxlintConfig; tab: OxlintConfig };
        quotes: { backtick: OxlintConfig; single: OxlintConfig };
        semiFalse: OxlintConfig;
      };
      tailwindcss: OxlintConfig;
      tsdoc: GeneratedFragmentData;
      unocss: {
        base: OxlintConfig;
        attributify: OxlintConfig;
        strict: OxlintConfig;
        attributifyStrict: OxlintConfig;
      };
      zod: GeneratedFragmentData;
    };
    unicorn: {
      allRecommended: GeneratedFragmentData;
      selected: GeneratedFragmentData;
    };
    jsx: GeneratedFragmentData;
    typescript: {
      app: {
        standard: GeneratedFragmentData;
        standardNonErasable: GeneratedFragmentData;
        typeAware: GeneratedFragmentData;
        typeAwareCustomScope: GeneratedFragmentData;
        typeAwareCustomScopeNonErasable: GeneratedFragmentData;
        typeAwareNonErasable: GeneratedFragmentData;
      };
      lib: {
        standard: GeneratedFragmentData;
        standardNonErasable: GeneratedFragmentData;
        typeAware: GeneratedFragmentData;
        typeAwareCustomScope: GeneratedFragmentData;
        typeAwareCustomScopeNonErasable: GeneratedFragmentData;
        typeAwareNonErasable: GeneratedFragmentData;
      };
    };
    test: {
      default: GeneratedFragmentData;
      editor: GeneratedFragmentData;
    };
    vue: {
      javascript: GeneratedFragmentData;
      javascriptV2: GeneratedFragmentData;
      typescript: GeneratedFragmentData;
      typescriptV2: GeneratedFragmentData;
    };
    react: {
      standard: GeneratedFragmentData;
      typeAware: GeneratedFragmentData;
    };
    nextjs: GeneratedFragmentData;
    jsdoc: {
      standard: GeneratedFragmentData;
      stylistic: GeneratedFragmentData;
    };
    tail: OxlintConfig;
  };
  report: CompatibilityReportData;
}

export interface OxlintArtifactDiff {
  changed: Array<string>;
  missing: Array<string>;
  unexpected: Array<string>;
}

type RenderedArtifacts = ReadonlyMap<string, string>;

async function migrateSource(
  source: Array<TypedFlatConfigItem>,
  reporter: MigrationReporter,
  options: MigrateSourceOptions = {},
): Promise<OxlintConfig> {
  const {
    defaultRuleFiles,
    jsPlugins = false,
    preserveDisabledRules = true,
    stripBaseline = true,
    typeAware = false,
  } = options;
  const prepared = prepareMigrationSource(
    preserveDisabledRules ? markDisabledRulesForMigration(source) : source,
    defaultRuleFiles,
  );
  const migrated = await migrate(prepared.configs, undefined, {
    jsPlugins,
    reporter,
    typeAware,
    withNursery: true,
  });
  const restoredRules = preserveDisabledRules
    ? restoreDisabledRulesAfterMigration(migrated)
    : migrated;
  const restored = restoreMigrationScopes(restoredRules, prepared.scopes);
  return normalizeOxlintConfig(restored, stripBaseline);
}

function variantCompatibility(
  config: OxlintConfig,
  reporter: MigrationReporter,
  options: VariantCompatibilityOptions,
): VariantCompatibility {
  const {
    adaptations = [],
    jsPlugins,
    recoveredRules = new Set(),
    sources,
  } = options;
  const skippedRules = Object.fromEntries(
    Object.entries(reporter.getSkippedRulesByCategory()).map(
      ([category, rules]) => [
        category,
        rules.filter((rule) => !recoveredRules.has(rule)),
      ],
    ),
  ) as SkippedRulesByCategory;
  const warnings = reporter.getWarnings();
  const isPartial =
    adaptations.length > 0 ||
    warnings.length > 0 ||
    Object.values(skippedRules).some((rules) => rules.length > 0);
  return {
    adaptations: [...adaptations],
    jsPlugins,
    migratedRuleCount: countConfiguredRules(config),
    skippedRules,
    sources: [...sources],
    status: isPartial ? "partial" : "supported",
    withNursery: true,
    warnings,
  };
}

async function generateBaseUnits(
  sourceUnits: ReadonlyArray<readonly [string, Array<TypedFlatConfigItem>]>,
): Promise<{ config: OxlintConfig; compatibility: VariantCompatibility }> {
  const reporter = new MigrationReporter();
  const migratedUnits: Array<OxlintConfig> = [];
  const recoveredRules = new Set<string>();

  for (const [name, source] of sourceUnits) {
    const migrated = await migrateSource(source, reporter, {
      jsPlugins: true,
      stripBaseline: false,
    });
    if (name !== "node") {
      migratedUnits.push(migrated);
      continue;
    }

    const fallback = createAliasedFallbackConfig(source, reporter, {
      fallback: {
        pluginName: "eslint-node",
        sourceRulePrefix: "n",
        specifier: "eslint-plugin-n",
        targetRulePrefix: "eslint-node",
      },
    });
    for (const rule of fallback.recoveredRules) recoveredRules.add(rule);
    migratedUnits.push(mergeOxlintConfigs([migrated, fallback.config]));
  }

  const config = mergeOxlintConfigs(migratedUnits);
  return {
    compatibility: variantCompatibility(config, reporter, {
      jsPlugins: true,
      recoveredRules,
      sources: sourceUnits.map(([name]) => name),
    }),
    config,
  };
}

async function generateBase(
  isInEditor: boolean,
): Promise<{ config: OxlintConfig; compatibility: VariantCompatibility }> {
  return await generateBaseUnits([
    ["ignores", await ignores()],
    ["javascript", await javascript({ isInEditor })],
    ["comments", await comments()],
    ["node", await node()],
    ["imports", await imports({ stylistic: false })],
  ]);
}

async function generateBaseSuffix(): Promise<{
  config: OxlintConfig;
  compatibility: VariantCompatibility;
}> {
  const javascriptConfigs = await javascript();
  const rulesIndex = javascriptConfigs.findIndex(
    (config) => config.name === "antfu/javascript/rules",
  );
  if (rulesIndex === -1)
    throw new Error(
      'Unable to locate the "antfu/javascript/rules" producer boundary',
    );

  return await generateBaseUnits([
    ["javascript.suffix", javascriptConfigs.slice(rulesIndex + 1)],
    ["comments", await comments()],
    ["node", await node()],
    ["imports", await imports({ stylistic: false })],
  ]);
}

async function generateFragment(options: GenerateFragmentOptions): Promise<{
  compatibility: VariantCompatibility;
  fragment: GeneratedFragmentData;
}> {
  const {
    adaptations = [],
    aliasedFallbacks = [],
    defaultRuleFiles,
    jsPlugins = false,
    source,
    sourceName,
    transform = (config) => config,
    typeAware = false,
  } = options;
  const overrideTarget = options.overrideTarget ?? { files: defaultRuleFiles };
  const reporter = new MigrationReporter();
  const migratedConfig = await migrateSource(source, reporter, {
    defaultRuleFiles,
    jsPlugins,
    typeAware,
  });
  const recoveredRules = new Set<string>();
  const fallbackConfigs = aliasedFallbacks.map((fallback) => {
    const result = createAliasedFallbackConfig(source, reporter, {
      defaultRuleFiles,
      fallback,
    });
    for (const rule of result.recoveredRules) recoveredRules.add(rule);
    return result.config;
  });
  const config = transform(
    mergeOxlintConfigs([migratedConfig, ...fallbackConfigs]),
  );

  return {
    compatibility: variantCompatibility(config, reporter, {
      jsPlugins: jsPlugins || aliasedFallbacks.length > 0,
      adaptations,
      recoveredRules,
      sources: [sourceName],
    }),
    fragment: {
      config,
      overrideTarget: {
        ...overrideTarget,
        ...(overrideTarget?.excludeFiles != null && {
          excludeFiles: translateOxlintGlobs(overrideTarget.excludeFiles),
        }),
        files: translateOxlintGlobs(overrideTarget?.files ?? defaultRuleFiles),
      },
    },
  };
}

async function generateRootVariant(
  sourceUnits: ReadonlyArray<RootSourceUnit>,
  transform: (config: OxlintConfig) => OxlintConfig = (config) => config,
  aliasedFallbacks: ReadonlyArray<AliasedFallback> = [],
): Promise<{ config: OxlintConfig; compatibility: VariantCompatibility }> {
  const reporter = new MigrationReporter();
  const migratedUnits: Array<OxlintConfig> = [];
  const recoveredRules = new Set<string>();

  for (const [, source, options] of sourceUnits) {
    migratedUnits.push(
      await migrateSource(source, reporter, {
        jsPlugins: options?.jsPlugins ?? true,
        preserveDisabledRules: options?.preserveDisabledRules ?? true,
        stripBaseline: false,
      }),
    );
  }

  const fallbackConfigs = sourceUnits.flatMap(([, source]) =>
    aliasedFallbacks.map((fallback) => {
      const result = createAliasedFallbackConfig(source, reporter, {
        fallback,
      });
      for (const rule of result.recoveredRules) recoveredRules.add(rule);
      return result.config;
    }),
  );
  const config = transform(
    mergeOxlintConfigs([...migratedUnits, ...fallbackConfigs]),
  );
  return {
    compatibility: variantCompatibility(config, reporter, {
      jsPlugins: true,
      recoveredRules,
      sources: sourceUnits.map(([name]) => name),
    }),
    config,
  };
}

function ensureRootJsPlugin(
  config: OxlintConfig,
  entry: { name: string; specifier: string },
): OxlintConfig {
  const entries = config.jsPlugins ?? [];
  const alreadyConfigured = entries.some((configured) =>
    typeof configured === "string"
      ? configured === entry.specifier
      : configured.name === entry.name,
  );
  return alreadyConfigured
    ? config
    : { ...config, jsPlugins: [...entries, entry] };
}

function createAliasedFallbackConfig(
  source: Array<TypedFlatConfigItem>,
  reporter: MigrationReporter,
  options: AliasedFallbackOptions,
): { config: OxlintConfig; recoveredRules: Set<string> } {
  const { defaultRuleFiles, fallback } = options;
  const skipped = reporter.getSkippedRulesByCategory();
  const categories = fallback.categories ?? [
    "js-plugins",
    "not-implemented",
    "unsupported",
  ];
  const skippedCandidates = new Set(
    categories.flatMap((category) => skipped[category]),
  );
  const candidates = fallback.includeConfiguredRules
    ? undefined
    : skippedCandidates;
  const recoveredRules = new Set<string>();
  const configs: Array<OxlintConfig> = [];

  for (const item of source) {
    const rules = Object.fromEntries(
      Object.entries(item.rules ?? {}).flatMap(([rule, value]) => {
        if (
          !rule.startsWith(`${fallback.sourceRulePrefix}/`) ||
          (candidates != null && !candidates.has(rule))
        )
          return [];
        if (skippedCandidates.has(rule)) recoveredRules.add(rule);
        return [
          [
            `${fallback.targetRulePrefix}${rule.slice(
              fallback.sourceRulePrefix.length,
            )}`,
            value,
          ],
        ];
      }),
    );
    if (Object.keys(rules).length === 0) continue;

    const jsPlugins = [
      { name: fallback.pluginName, specifier: fallback.specifier },
    ];
    const files = item.files ?? defaultRuleFiles;
    if (files == null) {
      configs.push({ jsPlugins, rules });
      continue;
    }
    if (files.some((file) => Array.isArray(file)))
      throw new TypeError(
        "Oxlint aliased fallbacks do not support ESLint AND file globs",
      );

    configs.push({
      overrides: [
        {
          ...(item.ignores != null && {
            excludeFiles: translateOxlintGlobs(item.ignores),
          }),
          files: translateOxlintGlobs(files as Array<string>),
          jsPlugins,
          rules,
        },
      ],
    });
  }

  return {
    config: mergeOxlintConfigs(configs),
    recoveredRules,
  };
}

function omitSourcePlugin(
  source: Array<TypedFlatConfigItem>,
  pluginName: string,
  rulePrefix: string = pluginName,
): Array<TypedFlatConfigItem> {
  return source.map((config) => ({
    ...config,
    ...(config.plugins != null && {
      plugins: Object.fromEntries(
        Object.entries(config.plugins).filter(([name]) => name !== pluginName),
      ),
    }),
    ...(config.rules != null && {
      rules: Object.fromEntries(
        Object.entries(config.rules).filter(
          ([rule]) => !rule.startsWith(`${rulePrefix}/`),
        ),
      ),
    }),
  }));
}

function omitSourcePlugins(
  source: Array<TypedFlatConfigItem>,
  pluginNames: ReadonlyArray<string>,
): Array<TypedFlatConfigItem> {
  return pluginNames.reduce(
    (configs, pluginName) => omitSourcePlugin(configs, pluginName),
    source,
  );
}

function omitSourceRules(
  source: Array<TypedFlatConfigItem>,
  omittedRules: ReadonlySet<string>,
): Array<TypedFlatConfigItem> {
  return source.map((config) => ({
    ...config,
    ...(config.rules != null && {
      rules: Object.fromEntries(
        Object.entries(config.rules).filter(
          ([rule]) => !omittedRules.has(rule),
        ),
      ),
    }),
  }));
}

function selectSourceRules(
  source: Array<TypedFlatConfigItem>,
  selectedRules: ReadonlySet<string>,
): Array<TypedFlatConfigItem> {
  return source.flatMap((config) => {
    const rules = Object.fromEntries(
      Object.entries(config.rules ?? {}).filter(([rule]) =>
        selectedRules.has(rule),
      ),
    );
    return Object.keys(rules).length > 0 ? [{ ...config, rules }] : [];
  });
}

function selectChangedSourceRules(
  source: Array<TypedFlatConfigItem>,
  baseline: Array<TypedFlatConfigItem>,
): Array<TypedFlatConfigItem> {
  const sourceRules = Object.assign(
    {},
    ...source.map((config) => config.rules ?? {}),
  ) as Record<string, unknown>;
  const baselineRules = Object.assign(
    {},
    ...baseline.map((config) => config.rules ?? {}),
  ) as Record<string, unknown>;
  const changedRules = new Set(
    source.flatMap((config) =>
      Object.entries(config.rules ?? {}).flatMap(([rule, value]) =>
        JSON.stringify(value) === JSON.stringify(baselineRules[rule])
          ? []
          : [rule],
      ),
    ),
  );
  const removedRules = new Set(
    Object.keys(baselineRules).filter(
      (rule) => !Object.hasOwn(sourceRules, rule),
    ),
  );
  const disables = selectSourceRules(baseline, removedRules).map((config) => ({
    ...config,
    rules: Object.fromEntries(
      Object.keys(config.rules ?? {}).map((rule) => [rule, "off"]),
    ),
  }));
  return [...selectSourceRules(source, changedRules), ...disables];
}

function isExecutableSolidConfig(config: TypedFlatConfigItem): boolean {
  return (
    config.name?.startsWith("antfu/solid") === true ||
    executableSolidConfigNames.has(config.name ?? "")
  );
}

function selectAngularTypeScriptSource(
  source: Array<TypedFlatConfigItem>,
): Array<TypedFlatConfigItem> {
  const setup = source.find((config) => config.name === "antfu/angular/setup");
  const rules = source.find(
    (config) => config.name === "antfu/angular/rules/ts",
  );
  const angularPlugin = setup?.plugins?.["@angular-eslint"];
  if (setup == null || rules == null || angularPlugin == null)
    throw new Error("Unable to isolate the Angular TypeScript config");

  const rulesWithoutProcessor = { ...rules };
  delete rulesWithoutProcessor.processor;
  return [
    { ...setup, plugins: { "@angular-eslint": angularPlugin } },
    rulesWithoutProcessor,
  ];
}

function selectI18nJavaScriptSource(
  source: Array<TypedFlatConfigItem>,
): Array<TypedFlatConfigItem> {
  const recommended = source.find((config) =>
    Object.hasOwn(config.rules ?? {}, "i18next/no-literal-string"),
  );
  if (recommended == null)
    throw new Error("Unable to isolate the i18next recommended config");
  return [recommended];
}

async function generateTypeScriptVariant(options: {
  erasableOnly: boolean;
  type: "app" | "lib";
  typeAware: boolean;
}): Promise<{
  compatibility: VariantCompatibility;
  fragment: GeneratedFragmentData;
}> {
  const { erasableOnly, type, typeAware } = options;
  const incompatiblePlugins = typeAware
    ? ["expect-type", "eslint-plugin-sort-destructure-keys-typescript"]
    : ["expect-type"];
  return await generateFragment({
    adaptations: [
      typeAware
        ? "eslint-plugin-expect-type and eslint-plugin-sort-destructure-keys-typescript are omitted because JavaScript plugins cannot access TypeScript parser services in Oxlint."
        : "eslint-plugin-expect-type is omitted because it depends on unsupported TypeScript parser services.",
    ],
    aliasedFallbacks: [
      {
        pluginName: "eslint-typescript",
        sourceRulePrefix: "@typescript-eslint",
        specifier: "@typescript-eslint/eslint-plugin",
        targetRulePrefix: "eslint-typescript",
      },
    ],
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    jsPlugins: true,
    source: omitSourcePlugins(
      await typescript({
        erasableOnly,
        ...(typeAware && { tsconfigPath: "tsconfig.json" }),
        type,
      }),
      incompatiblePlugins,
    ),
    sourceName: "typescript",
    typeAware,
  });
}

async function generateTypeAwareCustomScopeVariant(options: {
  erasableOnly: boolean;
  type: "app" | "lib";
}): Promise<{
  compatibility: VariantCompatibility;
  fragment: GeneratedFragmentData;
}> {
  const { erasableOnly, type } = options;
  return await generateFragment({
    adaptations: [
      "eslint-plugin-expect-type and eslint-plugin-sort-destructure-keys-typescript are omitted because JavaScript plugins cannot access TypeScript parser services in Oxlint.",
    ],
    aliasedFallbacks: [
      {
        pluginName: "eslint-typescript",
        sourceRulePrefix: "@typescript-eslint",
        specifier: "@typescript-eslint/eslint-plugin",
        targetRulePrefix: "eslint-typescript",
      },
    ],
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    jsPlugins: true,
    source: omitSourcePlugins(
      await typescript({
        erasableOnly,
        filesTypeAware: [typeAwareFilesPlaceholder],
        ignoresTypeAware: [typeAwareExcludesPlaceholder],
        tsconfigPath: "tsconfig.json",
        type,
      }),
      ["expect-type", "eslint-plugin-sort-destructure-keys-typescript"],
    ),
    sourceName: "typescript.typeAwareCustomScope",
    typeAware: true,
  });
}

async function generateVueVariant(options: {
  typescript: boolean;
  vueVersion: 2 | 3;
}): Promise<{
  compatibility: VariantCompatibility;
  fragment: GeneratedFragmentData;
}> {
  return await generateFragment({
    adaptations: [
      "Vue template, accessibility, custom-block, and SFC-block configs are omitted because Oxlint only exposes the script AST.",
    ],
    aliasedFallbacks: [
      antfuFallback,
      {
        includeConfiguredRules: true,
        pluginName: "eslint-node",
        sourceRulePrefix: "n",
        specifier: "eslint-plugin-n",
        targetRulePrefix: "eslint-node",
      },
      {
        categories: ["not-implemented"],
        pluginName: "eslint-vue",
        sourceRulePrefix: "vue",
        specifier: "eslint-plugin-vue",
        targetRulePrefix: "eslint-vue",
      },
    ],
    defaultRuleFiles: [GLOB_VUE],
    source: await vue({
      a11y: false,
      sfcBlocks: false,
      stylistic: false,
      typescript: options.typescript,
      vueVersion: options.vueVersion,
    }),
    sourceName: "vue",
  });
}

async function readPackageVersion(url: URL): Promise<string> {
  const packageJson = JSON.parse(await fs.readFile(url, "utf8")) as {
    version?: unknown;
  };
  if (typeof packageJson.version !== "string") {
    throw new TypeError(`Package at ${url.pathname} has no string version`);
  }
  return packageJson.version;
}

function compatibilityLimitations(): CompatibilityReportData["limitations"] {
  return [
    {
      classification: "runtime-requirement",
      description:
        "Compatible ESLint rules without native Oxlint implementations are emitted through Oxlint's JavaScript-plugin runtime and require their plugin packages.",
      id: "javascript-plugin-fallbacks",
    },
    {
      classification: "upstream",
      description:
        "Rules listed as skipped remain governed by @oxlint/migrate and Oxlint support in the pinned versions.",
      id: "upstream-rule-coverage",
    },
    {
      classification: "generated-adaptation",
      description:
        "ESLint override ignores are restored as Oxlint excludeFiles because the migrator does not preserve them.",
      id: "override-ignore-restoration",
    },
    {
      classification: "generated-adaptation",
      description:
        "Rule-bearing root items in optional integrations are scoped to that integration's default files.",
      id: "integration-rule-scoping",
    },
    {
      classification: "intentional-v1",
      description:
        "React variants are generated with package detection disabled, so their migrated react/only-export-components options are frozen and do not automatically adapt to installed Next.js, Vite, or Remix packages; the separately enabled Next.js fragment still applies its own rule.",
      id: "react-refresh-environment-detection",
    },
    {
      classification: "runtime-requirement",
      description:
        "Type-aware variants require oxlint-tsgolint at runtime and set options.typeAware.",
      id: "type-aware-runtime",
    },
    {
      classification: "upstream",
      description:
        "JavaScript plugins cannot access TypeScript parser services in Oxlint. React therefore reuses its parser-service-independent fallback fragment when native TypeScript type-aware rules are enabled.",
      id: "javascript-plugin-parser-services",
    },
    {
      classification: "upstream",
      description:
        "Custom ESLint parsers and processors are not executable by Oxlint; JSONC, YAML, TOML, Markdown, framework templates, and formatter execution remain ESLint-only.",
      id: "custom-language-runtime",
    },
  ];
}

async function generateData(): Promise<GeneratedData> {
  const variants: Record<string, VariantCompatibility> = {};

  const baseDefault = await generateBase(false);
  variants["base.default"] = baseDefault.compatibility;
  const baseEditor = await generateBase(true);
  variants["base.editor"] = baseEditor.compatibility;
  const baseSuffix = await generateBaseSuffix();
  variants["base.suffix"] = baseSuffix.compatibility;

  const commandFragment = await generateRootVariant([
    ["command", await command()],
  ]);
  variants.command = commandFragment.compatibility;

  const e18eAppBaseSource = await e18e({
    modernization: false,
    moduleReplacements: false,
    performanceImprovements: false,
    type: "app",
  });
  const e18eLibBaseSource = await e18e({
    modernization: false,
    moduleReplacements: false,
    performanceImprovements: false,
    type: "lib",
  });
  const e18eAppDefault = await generateRootVariant([
    ["e18e", await e18e({ isInEditor: false, type: "app" })],
  ]);
  variants["e18e.app.default"] = e18eAppDefault.compatibility;
  const e18eAppEditor = await generateRootVariant([
    ["e18e", await e18e({ isInEditor: true, type: "app" })],
  ]);
  variants["e18e.app.editor"] = e18eAppEditor.compatibility;
  const e18eLibDefault = await generateRootVariant([
    ["e18e", await e18e({ isInEditor: false, type: "lib" })],
  ]);
  variants["e18e.lib.default"] = e18eLibDefault.compatibility;
  const e18eLibEditor = await generateRootVariant([
    ["e18e", await e18e({ isInEditor: true, type: "lib" })],
  ]);
  variants["e18e.lib.editor"] = e18eLibEditor.compatibility;
  const e18eBaseApp = await generateRootVariant(
    [["e18e.base", e18eAppBaseSource]],
    (config) =>
      ensureRootJsPlugin(config, {
        name: "e18e",
        specifier: "@e18e/eslint-plugin",
      }),
  );
  variants["e18e.base.app"] = e18eBaseApp.compatibility;
  const e18eBaseLib = await generateRootVariant(
    [["e18e.base", e18eLibBaseSource]],
    (config) =>
      ensureRootJsPlugin(config, {
        name: "e18e",
        specifier: "@e18e/eslint-plugin",
      }),
  );
  variants["e18e.base.lib"] = e18eBaseLib.compatibility;
  const e18eModernization = await generateRootVariant([
    [
      "e18e.modernization",
      selectChangedSourceRules(
        await e18e({
          modernization: true,
          moduleReplacements: false,
          performanceImprovements: false,
          type: "app",
        }),
        e18eAppBaseSource,
      ),
    ],
  ]);
  variants["e18e.modernization"] = e18eModernization.compatibility;
  const e18eModuleReplacements = await generateRootVariant([
    [
      "e18e.moduleReplacements",
      selectChangedSourceRules(
        await e18e({
          modernization: false,
          moduleReplacements: true,
          performanceImprovements: false,
          type: "app",
        }),
        e18eAppBaseSource,
      ),
    ],
  ]);
  variants["e18e.moduleReplacements"] = e18eModuleReplacements.compatibility;
  const e18ePerformanceImprovementsApp = await generateRootVariant([
    [
      "e18e.performanceImprovements",
      selectChangedSourceRules(
        await e18e({
          modernization: false,
          moduleReplacements: false,
          performanceImprovements: true,
          type: "app",
        }),
        e18eAppBaseSource,
      ),
    ],
  ]);
  variants["e18e.performanceImprovements.app"] =
    e18ePerformanceImprovementsApp.compatibility;
  const e18ePerformanceImprovementsLib = await generateRootVariant([
    [
      "e18e.performanceImprovements",
      selectChangedSourceRules(
        await e18e({
          modernization: false,
          moduleReplacements: false,
          performanceImprovements: true,
          type: "lib",
        }),
        e18eLibBaseSource,
      ),
    ],
  ]);
  variants["e18e.performanceImprovements.lib"] =
    e18ePerformanceImprovementsLib.compatibility;

  const regexpError = await generateRootVariant([
    ["regexp", await regexp({ level: "error" })],
  ]);
  variants["regexp.error"] = regexpError.compatibility;
  const regexpWarn = await generateRootVariant([
    ["regexp", await regexp({ level: "warn" })],
  ]);
  variants["regexp.warn"] = regexpWarn.compatibility;

  const perfectionistFragment = await generateRootVariant([
    ["perfectionist", await perfectionist()],
  ]);
  variants.perfectionist = perfectionistFragment.compatibility;
  const queryFragment = await generateRootVariant([["query", await query()]]);
  variants.query = queryFragment.compatibility;
  const angularTypeScript = await generateFragment({
    adaptations: [
      "Angular HTML templates and the inline-template processor are omitted because Oxlint cannot execute the Angular template parser or processors; executable TypeScript rules are retained.",
    ],
    defaultRuleFiles: [GLOB_TS],
    jsPlugins: true,
    source: selectAngularTypeScriptSource(await angular()),
    sourceName: "angular.typescript",
  });
  variants["angular.typescript"] = angularTypeScript.compatibility;
  const i18nJavaScript = await generateFragment({
    adaptations: [
      "Locale JSON validation, translation-key path validation, and prefix checks are omitted because they require unsupported JSON parsing or legacy plugin behavior; the executable i18next JavaScript/JSX rule is retained.",
    ],
    defaultRuleFiles: [GLOB_SRC],
    jsPlugins: true,
    source: selectI18nJavaScriptSource(await i18n()),
    sourceName: "i18n.javascript",
  });
  variants["i18n.javascript"] = i18nJavaScript.compatibility;
  const securityFragment = await generateRootVariant([
    ["security", await security()],
  ]);
  variants.security = securityFragment.compatibility;
  const solidJavaScript = await generateFragment({
    adaptations: [
      "Embedded React, JSX-a11y, and eslint-plugin-ssr-friendly presets are omitted; executable Solid rules and Solid-specific disables are retained, except obsolete SonarJS rule IDs absent from the installed plugin.",
    ],
    defaultRuleFiles: [GLOB_JSX, GLOB_TSX],
    jsPlugins: true,
    source: omitSourceRules(
      (await solid({ typescript: false })).filter((config) =>
        isExecutableSolidConfig(config),
      ),
      new Set([
        "sonarjs/jsx-no-constructed-context-values",
        "sonarjs/no-unstable-nested-components",
      ]),
    ),
    sourceName: "solid",
  });
  variants["solid.javascript"] = solidJavaScript.compatibility;
  const solidTypeScript = await generateFragment({
    adaptations: [
      "Embedded React, JSX-a11y, and eslint-plugin-ssr-friendly presets are omitted; executable Solid rules and Solid-specific disables are retained, except obsolete SonarJS rule IDs absent from the installed plugin.",
    ],
    defaultRuleFiles: [GLOB_JSX, GLOB_TSX],
    jsPlugins: true,
    source: omitSourceRules(
      (await solid({ typescript: true })).filter((config) =>
        isExecutableSolidConfig(config),
      ),
      new Set([
        "sonarjs/jsx-no-constructed-context-values",
        "sonarjs/no-unstable-nested-components",
      ]),
    ),
    sourceName: "solid",
  });
  variants["solid.typescript"] = solidTypeScript.compatibility;
  const solidReactDisables = await generateFragment({
    adaptations: [
      "The obsolete @eslint-react/prefer-destructuring-assignment disable is omitted because the installed plugin no longer defines that rule.",
    ],
    defaultRuleFiles: [GLOB_JSX, GLOB_TSX],
    jsPlugins: true,
    source: omitSourceRules(
      (await solid({ typescript: true })).filter(
        (config) => config.name === solidReactRulesOffConfigName,
      ),
      new Set(["@eslint-react/prefer-destructuring-assignment"]),
    ),
    sourceName: "solid.reactDisables",
  });
  variants["solid.reactDisables"] = solidReactDisables.compatibility;
  const storybookFragment = await generateRootVariant([
    ["storybook", await storybook()],
  ]);
  variants.storybook = storybookFragment.compatibility;
  const stylisticBaselineSource = await stylistic({
    jsx: true,
    lessOpinionated: false,
  });
  const stylisticDefault = await generateRootVariant([
    ["stylistic", stylisticBaselineSource],
  ]);
  variants.stylistic = stylisticDefault.compatibility;
  const stylisticNoJsx = await generateRootVariant([
    ["stylistic", await stylistic({ jsx: false, lessOpinionated: false })],
  ]);
  variants["stylistic.noJsx"] = stylisticNoJsx.compatibility;
  const stylisticLessOpinionated = await generateRootVariant([
    ["stylistic", await stylistic({ jsx: true, lessOpinionated: true })],
  ]);
  variants["stylistic.lessOpinionated"] =
    stylisticLessOpinionated.compatibility;
  const stylisticLessOpinionatedNoJsx = await generateRootVariant([
    ["stylistic", await stylistic({ jsx: false, lessOpinionated: true })],
  ]);
  variants["stylistic.lessOpinionated.noJsx"] =
    stylisticLessOpinionatedNoJsx.compatibility;
  const stylisticBraceStyleOneTrueBrace = await generateRootVariant([
    [
      "stylistic.braceStyle.1tbs",
      selectChangedSourceRules(
        await stylistic({ braceStyle: "1tbs" }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.braceStyle.1tbs"] =
    stylisticBraceStyleOneTrueBrace.compatibility;
  const stylisticBraceStyleAllman = await generateRootVariant([
    [
      "stylistic.braceStyle.allman",
      selectChangedSourceRules(
        await stylistic({ braceStyle: "allman" }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.braceStyle.allman"] =
    stylisticBraceStyleAllman.compatibility;
  const stylisticExperimental = await generateRootVariant(
    [
      [
        "stylistic.experimental",
        selectChangedSourceRules(
          await stylistic({ experimental: true }),
          stylisticBaselineSource,
        ),
      ],
    ],
    (config) =>
      ensureRootJsPlugin(
        {
          ...config,
          rules: {
            ...config.rules,
            "antfu/consistent-list-newline": "off",
          },
        },
        { name: "antfu", specifier: "eslint-plugin-antfu" },
      ),
  );
  variants["stylistic.experimental"] = stylisticExperimental.compatibility;
  const stylisticIndentNumberTemplate = await generateRootVariant([
    [
      "stylistic.indent.numberTemplate",
      selectChangedSourceRules(
        await stylistic({ indent: 17 }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.indent.numberTemplate"] =
    stylisticIndentNumberTemplate.compatibility;
  const stylisticIndentTab = await generateRootVariant([
    [
      "stylistic.indent.tab",
      selectChangedSourceRules(
        await stylistic({ indent: "tab" }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.indent.tab"] = stylisticIndentTab.compatibility;
  const stylisticQuotesBacktick = await generateRootVariant([
    [
      "stylistic.quotes.backtick",
      selectChangedSourceRules(
        await stylistic({ quotes: "backtick" }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.quotes.backtick"] = stylisticQuotesBacktick.compatibility;
  const stylisticQuotesSingle = await generateRootVariant([
    [
      "stylistic.quotes.single",
      selectChangedSourceRules(
        await stylistic({ quotes: "single" }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.quotes.single"] = stylisticQuotesSingle.compatibility;
  const stylisticSemiFalse = await generateRootVariant([
    [
      "stylistic.semi.false",
      selectChangedSourceRules(
        await stylistic({ semi: false }),
        stylisticBaselineSource,
      ),
    ],
  ]);
  variants["stylistic.semi.false"] = stylisticSemiFalse.compatibility;
  const importsStylisticFragment = await generateRootVariant(
    [
      [
        "imports",
        selectSourceRules(
          await imports({ stylistic: true }),
          new Set(["import-x/newline-after-import"]),
        ),
      ],
    ],
    (config) => config,
    [
      {
        pluginName: "eslint-import-x",
        sourceRulePrefix: "import-x",
        specifier: "eslint-plugin-import-x",
        targetRulePrefix: "eslint-import-x",
      },
    ],
  );
  variants["imports.stylistic"] = importsStylisticFragment.compatibility;
  const tailwindcssFragment = await generateRootVariant([
    ["tailwindcss", await tailwindcss()],
  ]);
  variants.tailwindcss = tailwindcssFragment.compatibility;
  const tsdocFragment = await generateFragment({
    defaultRuleFiles: [GLOB_TS, GLOB_TSX],
    jsPlugins: true,
    source: await tsdoc(),
    sourceName: "tsdoc",
  });
  variants.tsdoc = tsdocFragment.compatibility;
  const unocssBase = await generateRootVariant([
    ["unocss", await unocss({ attributify: false, strict: false })],
  ]);
  variants["unocss.base"] = unocssBase.compatibility;
  const unocssAttributify = await generateRootVariant([
    ["unocss", await unocss({ attributify: true, strict: false })],
  ]);
  variants["unocss.attributify"] = unocssAttributify.compatibility;
  const unocssStrict = await generateRootVariant([
    ["unocss", await unocss({ attributify: false, strict: true })],
  ]);
  variants["unocss.strict"] = unocssStrict.compatibility;
  const unocssAttributifyStrict = await generateRootVariant([
    ["unocss", await unocss({ attributify: true, strict: true })],
  ]);
  variants["unocss.attributifyStrict"] = unocssAttributifyStrict.compatibility;
  const zodFragment = await generateFragment({
    defaultRuleFiles: [GLOB_SRC],
    jsPlugins: true,
    source: await zod(),
    sourceName: "zod",
  });
  variants.zod = zodFragment.compatibility;

  const unicornAllRecommended = await generateFragment({
    aliasedFallbacks: [
      {
        pluginName: "eslint-unicorn",
        sourceRulePrefix: "unicorn",
        specifier: "eslint-plugin-unicorn",
        targetRulePrefix: "eslint-unicorn",
      },
    ],
    defaultRuleFiles: [GLOB_SRC],
    source: await unicorn({ allRecommended: true }),
    sourceName: "unicorn",
  });
  variants["unicorn.allRecommended"] = unicornAllRecommended.compatibility;
  const unicornSelected = await generateFragment({
    aliasedFallbacks: [
      {
        pluginName: "eslint-unicorn",
        sourceRulePrefix: "unicorn",
        specifier: "eslint-plugin-unicorn",
        targetRulePrefix: "eslint-unicorn",
      },
    ],
    defaultRuleFiles: [GLOB_SRC],
    source: await unicorn({ allRecommended: false }),
    sourceName: "unicorn",
  });
  variants["unicorn.selected"] = unicornSelected.compatibility;

  const jsxFragment = await generateFragment({
    defaultRuleFiles: [GLOB_JSX, GLOB_TSX],
    jsPlugins: true,
    source: await jsx(),
    sourceName: "jsx",
  });
  variants.jsx = jsxFragment.compatibility;

  const typescriptAppStandard = await generateTypeScriptVariant({
    erasableOnly: true,
    type: "app",
    typeAware: false,
  });
  variants["typescript.app.standard"] = typescriptAppStandard.compatibility;
  const typescriptAppTypeAware = await generateTypeScriptVariant({
    erasableOnly: true,
    type: "app",
    typeAware: true,
  });
  variants["typescript.app.typeAware"] = typescriptAppTypeAware.compatibility;
  const typescriptAppStandardNonErasable = await generateTypeScriptVariant({
    erasableOnly: false,
    type: "app",
    typeAware: false,
  });
  variants["typescript.app.standard.nonErasable"] =
    typescriptAppStandardNonErasable.compatibility;
  const typescriptAppTypeAwareNonErasable = await generateTypeScriptVariant({
    erasableOnly: false,
    type: "app",
    typeAware: true,
  });
  variants["typescript.app.typeAware.nonErasable"] =
    typescriptAppTypeAwareNonErasable.compatibility;
  const typescriptLibraryStandard = await generateTypeScriptVariant({
    erasableOnly: true,
    type: "lib",
    typeAware: false,
  });
  variants["typescript.lib.standard"] = typescriptLibraryStandard.compatibility;
  const typescriptLibraryTypeAware = await generateTypeScriptVariant({
    erasableOnly: true,
    type: "lib",
    typeAware: true,
  });
  variants["typescript.lib.typeAware"] =
    typescriptLibraryTypeAware.compatibility;
  const typescriptLibraryStandardNonErasable = await generateTypeScriptVariant({
    erasableOnly: false,
    type: "lib",
    typeAware: false,
  });
  variants["typescript.lib.standard.nonErasable"] =
    typescriptLibraryStandardNonErasable.compatibility;
  const typescriptLibraryTypeAwareNonErasable = await generateTypeScriptVariant(
    {
      erasableOnly: false,
      type: "lib",
      typeAware: true,
    },
  );
  variants["typescript.lib.typeAware.nonErasable"] =
    typescriptLibraryTypeAwareNonErasable.compatibility;
  const typescriptAppTypeAwareCustomScope =
    await generateTypeAwareCustomScopeVariant({
      erasableOnly: true,
      type: "app",
    });
  variants["typescript.app.typeAware.customScope"] =
    typescriptAppTypeAwareCustomScope.compatibility;
  const typescriptAppTypeAwareCustomScopeNonErasable =
    await generateTypeAwareCustomScopeVariant({
      erasableOnly: false,
      type: "app",
    });
  variants["typescript.app.typeAware.customScope.nonErasable"] =
    typescriptAppTypeAwareCustomScopeNonErasable.compatibility;
  const typescriptLibraryTypeAwareCustomScope =
    await generateTypeAwareCustomScopeVariant({
      erasableOnly: true,
      type: "lib",
    });
  variants["typescript.lib.typeAware.customScope"] =
    typescriptLibraryTypeAwareCustomScope.compatibility;
  const typescriptLibraryTypeAwareCustomScopeNonErasable =
    await generateTypeAwareCustomScopeVariant({
      erasableOnly: false,
      type: "lib",
    });
  variants["typescript.lib.typeAware.customScope.nonErasable"] =
    typescriptLibraryTypeAwareCustomScopeNonErasable.compatibility;

  const testDefault = await generateFragment({
    aliasedFallbacks: [
      antfuFallback,
      {
        includeConfiguredRules: true,
        pluginName: "eslint-node",
        sourceRulePrefix: "n",
        specifier: "eslint-plugin-n",
        targetRulePrefix: "eslint-node",
      },
      {
        pluginName: "eslint-no-only-tests",
        sourceRulePrefix: "vitest",
        specifier: "eslint-plugin-no-only-tests",
        targetRulePrefix: "eslint-no-only-tests",
      },
    ],
    defaultRuleFiles: GLOB_TESTS,
    source: await test({ isInEditor: false }),
    sourceName: "test",
  });
  variants["test.default"] = testDefault.compatibility;
  const testEditor = await generateFragment({
    aliasedFallbacks: [
      antfuFallback,
      {
        includeConfiguredRules: true,
        pluginName: "eslint-node",
        sourceRulePrefix: "n",
        specifier: "eslint-plugin-n",
        targetRulePrefix: "eslint-node",
      },
      {
        pluginName: "eslint-no-only-tests",
        sourceRulePrefix: "vitest",
        specifier: "eslint-plugin-no-only-tests",
        targetRulePrefix: "eslint-no-only-tests",
      },
    ],
    defaultRuleFiles: GLOB_TESTS,
    source: await test({ isInEditor: true }),
    sourceName: "test",
  });
  variants["test.editor"] = testEditor.compatibility;

  const vueJavaScript = await generateVueVariant({
    typescript: false,
    vueVersion: 3,
  });
  variants["vue.javascript"] = vueJavaScript.compatibility;
  const vueJavaScriptV2 = await generateVueVariant({
    typescript: false,
    vueVersion: 2,
  });
  variants["vue.javascript.v2"] = vueJavaScriptV2.compatibility;
  const vueTypeScript = await generateVueVariant({
    typescript: true,
    vueVersion: 3,
  });
  variants["vue.typescript"] = vueTypeScript.compatibility;
  const vueTypeScriptV2 = await generateVueVariant({
    typescript: true,
    vueVersion: 2,
  });
  variants["vue.typescript.v2"] = vueTypeScriptV2.compatibility;

  const neutralReactEnvironment = { hasPackage: () => false };
  const reactStandard = await generateFragment({
    adaptations: [
      "eslint-plugin-ssr-friendly is omitted because it uses ESLint APIs that Oxlint's JavaScript-plugin runtime does not implement.",
    ],
    defaultRuleFiles: [GLOB_SRC],
    jsPlugins: true,
    source: omitSourcePlugin(
      await react({}, neutralReactEnvironment),
      "ssr-friendly",
    ),
    sourceName: "react",
  });
  variants["react.standard"] = reactStandard.compatibility;
  // Oxlint's JavaScript-plugin API does not expose TypeScript parser services.
  // The ESLint type-checked React preset and classname-components rules would
  // throw before linting every TS/TSX file, so native type-aware TypeScript
  // remains enabled by its own fragment while React uses the executable preset.
  const reactTypeAware = {
    compatibility: {
      ...reactStandard.compatibility,
      adaptations: [
        ...reactStandard.compatibility.adaptations,
        "Type-aware React JavaScript-plugin rules, including classname-components, are omitted because Oxlint does not expose TypeScript parser services to JavaScript plugins.",
      ],
      status: "partial" as const,
    },
    fragment: reactStandard.fragment,
  };
  variants["react.typeAware"] = reactTypeAware.compatibility;

  const nextjsFragment = await generateFragment({
    aliasedFallbacks: [
      {
        pluginName: "eslint-next",
        sourceRulePrefix: "@next/next",
        specifier: "@next/eslint-plugin-next",
        targetRulePrefix: "eslint-next",
      },
    ],
    defaultRuleFiles: [GLOB_SRC],
    source: await nextjs(),
    sourceName: "nextjs",
  });
  variants.nextjs = nextjsFragment.compatibility;
  const jsdocStandard = await generateFragment({
    aliasedFallbacks: [
      {
        pluginName: "eslint-jsdoc",
        sourceRulePrefix: "jsdoc",
        specifier: "eslint-plugin-jsdoc",
        targetRulePrefix: "eslint-jsdoc",
      },
    ],
    defaultRuleFiles: [GLOB_SRC],
    source: await jsdoc({ stylistic: false }),
    sourceName: "jsdoc",
  });
  variants["jsdoc.standard"] = jsdocStandard.compatibility;
  const jsdocStylistic = await generateFragment({
    aliasedFallbacks: [
      {
        pluginName: "eslint-jsdoc",
        sourceRulePrefix: "jsdoc",
        specifier: "eslint-plugin-jsdoc",
        targetRulePrefix: "eslint-jsdoc",
      },
    ],
    defaultRuleFiles: [GLOB_SRC],
    source: await jsdoc({ stylistic: true }),
    sourceName: "jsdoc",
  });
  variants["jsdoc.stylistic"] = jsdocStylistic.compatibility;

  const tail = await generateRootVariant(
    [
      ["default-import-name", await defaultImportName()],
      ["prettier", await prettier(), { jsPlugins: false }],
      ["disables", await disables()],
    ],
    (config) => config,
    [
      {
        includeConfiguredRules: true,
        pluginName: "eslint-unicorn",
        sourceRulePrefix: "unicorn",
        specifier: "eslint-plugin-unicorn",
        targetRulePrefix: "eslint-unicorn",
      },
    ],
  );
  variants.tail = tail.compatibility;

  const [migrateVersion, oxlintVersion] = await Promise.all([
    readPackageVersion(
      new URL(
        "../../node_modules/@oxlint/migrate/package.json",
        import.meta.url,
      ),
    ),
    readPackageVersion(
      new URL("../../node_modules/oxlint/package.json", import.meta.url),
    ),
  ]);

  return {
    fragments: {
      base: {
        default: baseDefault.config,
        editor: baseEditor.config,
        suffix: baseSuffix.config,
      },
      command: commandFragment.config,
      e18e: {
        app: {
          default: e18eAppDefault.config,
          editor: e18eAppEditor.config,
        },
        base: {
          app: e18eBaseApp.config,
          lib: e18eBaseLib.config,
        },
        lib: {
          default: e18eLibDefault.config,
          editor: e18eLibEditor.config,
        },
        modernization: e18eModernization.config,
        moduleReplacements: e18eModuleReplacements.config,
        performanceImprovements: {
          app: e18ePerformanceImprovementsApp.config,
          lib: e18ePerformanceImprovementsLib.config,
        },
      },
      regexp: {
        error: regexpError.config,
        warn: regexpWarn.config,
      },
      integrations: {
        angular: angularTypeScript.fragment,
        i18n: i18nJavaScript.fragment,
        importsStylistic: importsStylisticFragment.config,
        perfectionist: perfectionistFragment.config,
        query: queryFragment.config,
        security: securityFragment.config,
        solid: {
          javascript: solidJavaScript.fragment,
          reactDisables: solidReactDisables.fragment,
          typescript: solidTypeScript.fragment,
        },
        storybook: storybookFragment.config,
        stylistic: {
          default: stylisticDefault.config,
          lessOpinionated: stylisticLessOpinionated.config,
          lessOpinionatedNoJsx: stylisticLessOpinionatedNoJsx.config,
          noJsx: stylisticNoJsx.config,
        },
        stylisticCustomizations: {
          braceStyle: {
            allman: stylisticBraceStyleAllman.config,
            oneTrueBrace: stylisticBraceStyleOneTrueBrace.config,
          },
          experimental: stylisticExperimental.config,
          indent: {
            numberTemplate: stylisticIndentNumberTemplate.config,
            tab: stylisticIndentTab.config,
          },
          quotes: {
            backtick: stylisticQuotesBacktick.config,
            single: stylisticQuotesSingle.config,
          },
          semiFalse: stylisticSemiFalse.config,
        },
        tailwindcss: tailwindcssFragment.config,
        tsdoc: tsdocFragment.fragment,
        unocss: {
          base: unocssBase.config,
          attributify: unocssAttributify.config,
          strict: unocssStrict.config,
          attributifyStrict: unocssAttributifyStrict.config,
        },
        zod: zodFragment.fragment,
      },
      unicorn: {
        allRecommended: unicornAllRecommended.fragment,
        selected: unicornSelected.fragment,
      },
      jsx: jsxFragment.fragment,
      typescript: {
        app: {
          standard: typescriptAppStandard.fragment,
          standardNonErasable: typescriptAppStandardNonErasable.fragment,
          typeAware: typescriptAppTypeAware.fragment,
          typeAwareCustomScope: typescriptAppTypeAwareCustomScope.fragment,
          typeAwareCustomScopeNonErasable:
            typescriptAppTypeAwareCustomScopeNonErasable.fragment,
          typeAwareNonErasable: typescriptAppTypeAwareNonErasable.fragment,
        },
        lib: {
          standard: typescriptLibraryStandard.fragment,
          standardNonErasable: typescriptLibraryStandardNonErasable.fragment,
          typeAware: typescriptLibraryTypeAware.fragment,
          typeAwareCustomScope: typescriptLibraryTypeAwareCustomScope.fragment,
          typeAwareCustomScopeNonErasable:
            typescriptLibraryTypeAwareCustomScopeNonErasable.fragment,
          typeAwareNonErasable: typescriptLibraryTypeAwareNonErasable.fragment,
        },
      },
      test: {
        default: testDefault.fragment,
        editor: testEditor.fragment,
      },
      vue: {
        javascript: vueJavaScript.fragment,
        javascriptV2: vueJavaScriptV2.fragment,
        typescript: vueTypeScript.fragment,
        typescriptV2: vueTypeScriptV2.fragment,
      },
      react: {
        standard: reactStandard.fragment,
        typeAware: reactTypeAware.fragment,
      },
      nextjs: nextjsFragment.fragment,
      jsdoc: {
        standard: jsdocStandard.fragment,
        stylistic: jsdocStylistic.fragment,
      },
      tail: tail.config,
    },
    report: {
      generation: {
        jsPlugins: "per-variant",
        typeAware: "per-variant",
        withNursery: true,
      },
      limitations: compatibilityLimitations(),
      schemaVersion: 3,
      variants,
      versions: {
        migrate: migrateVersion,
        oxlint: oxlintVersion,
      },
    },
  };
}

function renderValue(value: unknown): string {
  return JSON.stringify(sortGeneratedValue(value), null, 2);
}

function renderFragments(fragments: GeneratedData["fragments"]): string {
  return `${banner}import type { OxlintConfig } from "oxlint";

export interface GeneratedFragment {
  config: OxlintConfig;
  overrideTarget?: {
    excludeFiles?: Array<string>;
    files: Array<string>;
  };
}

export interface GeneratedOxlintFragments {
  base: { default: OxlintConfig; editor: OxlintConfig; suffix: OxlintConfig };
  command: OxlintConfig;
  e18e: {
    app: { default: OxlintConfig; editor: OxlintConfig };
    base: { app: OxlintConfig; lib: OxlintConfig };
    lib: { default: OxlintConfig; editor: OxlintConfig };
    modernization: OxlintConfig;
    moduleReplacements: OxlintConfig;
    performanceImprovements: { app: OxlintConfig; lib: OxlintConfig };
  };
  regexp: { error: OxlintConfig; warn: OxlintConfig };
  integrations: {
    angular: GeneratedFragment;
    i18n: GeneratedFragment;
    importsStylistic: OxlintConfig;
    perfectionist: OxlintConfig;
    query: OxlintConfig;
    security: OxlintConfig;
    solid: {
      javascript: GeneratedFragment;
      reactDisables: GeneratedFragment;
      typescript: GeneratedFragment;
    };
    storybook: OxlintConfig;
    stylistic: {
      default: OxlintConfig;
      lessOpinionated: OxlintConfig;
      lessOpinionatedNoJsx: OxlintConfig;
      noJsx: OxlintConfig;
    };
    stylisticCustomizations: {
      braceStyle: { allman: OxlintConfig; oneTrueBrace: OxlintConfig };
      experimental: OxlintConfig;
      indent: { numberTemplate: OxlintConfig; tab: OxlintConfig };
      quotes: { backtick: OxlintConfig; single: OxlintConfig };
      semiFalse: OxlintConfig;
    };
    tailwindcss: OxlintConfig;
    tsdoc: GeneratedFragment;
    unocss: {
      base: OxlintConfig;
      attributify: OxlintConfig;
      strict: OxlintConfig;
      attributifyStrict: OxlintConfig;
    };
    zod: GeneratedFragment;
  };
  unicorn: { allRecommended: GeneratedFragment; selected: GeneratedFragment };
  jsx: GeneratedFragment;
  typescript: {
    app: {
      standard: GeneratedFragment;
      standardNonErasable: GeneratedFragment;
      typeAware: GeneratedFragment;
      typeAwareCustomScope: GeneratedFragment;
      typeAwareCustomScopeNonErasable: GeneratedFragment;
      typeAwareNonErasable: GeneratedFragment;
    };
    lib: {
      standard: GeneratedFragment;
      standardNonErasable: GeneratedFragment;
      typeAware: GeneratedFragment;
      typeAwareCustomScope: GeneratedFragment;
      typeAwareCustomScopeNonErasable: GeneratedFragment;
      typeAwareNonErasable: GeneratedFragment;
    };
  };
  test: { default: GeneratedFragment; editor: GeneratedFragment };
  vue: {
    javascript: GeneratedFragment;
    javascriptV2: GeneratedFragment;
    typescript: GeneratedFragment;
    typescriptV2: GeneratedFragment;
  };
  react: { standard: GeneratedFragment; typeAware: GeneratedFragment };
  nextjs: GeneratedFragment;
  jsdoc: { standard: GeneratedFragment; stylistic: GeneratedFragment };
  tail: OxlintConfig;
}

export const generatedOxlintFragments: GeneratedOxlintFragments = ${renderValue(
    fragments,
  )};
`;
}

function renderCompatibilityReport(report: CompatibilityReportData): string {
  return `${banner}export type OxlintLimitationClassification =
  | "generated-adaptation"
  | "intentional-v1"
  | "runtime-requirement"
  | "upstream";

export type OxlintSkippedRuleCategory =
  | "js-plugins"
  | "not-implemented"
  | "nursery"
  | "type-aware"
  | "unsupported";

export interface OxlintVariantCompatibility {
  adaptations: Array<string>;
  jsPlugins: boolean;
  migratedRuleCount: number;
  skippedRules: Record<OxlintSkippedRuleCategory, Array<string>>;
  sources: Array<string>;
  status: "partial" | "supported";
  withNursery: boolean;
  warnings: Array<string>;
}

export interface OxlintCompatibilityReport {
  generation: {
    jsPlugins: "per-variant";
    typeAware: "per-variant";
    withNursery: true;
  };
  limitations: Array<{
    classification: OxlintLimitationClassification;
    description: string;
    id: string;
  }>;
  schemaVersion: 3;
  variants: Record<string, OxlintVariantCompatibility>;
  versions: { migrate: string; oxlint: string };
}

export const oxlintCompatibilityReport: OxlintCompatibilityReport = ${renderValue(
    report,
  )};
`;
}

export async function renderOxlintArtifacts(): Promise<Map<string, string>> {
  const data = await generateData();
  return new Map([
    [
      `${generatedDirectory}/compatibility-report.ts`,
      renderCompatibilityReport(data.report),
    ],
    [`${generatedDirectory}/fragments.ts`, renderFragments(data.fragments)],
    [
      `${generatedDirectory}/index.ts`,
      `${banner}export * from "./compatibility-report";\nexport * from "./fragments";\n`,
    ],
  ]);
}

async function listFiles(directory: string): Promise<Array<string>> {
  let entries;
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }

  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      return entry.isDirectory() ? await listFiles(entryPath) : [entryPath];
    }),
  );
  return files.flat().toSorted((left, right) => left.localeCompare(right));
}

export function normalizeOxlintArtifactPath(relativePath: string): string {
  return relativePath.replaceAll(path.win32.sep, () => path.posix.sep);
}

export async function diffOxlintArtifacts(
  root: string,
  rendered: RenderedArtifacts,
): Promise<OxlintArtifactDiff> {
  const expectedFiles = [...rendered.keys()].toSorted((left, right) =>
    left.localeCompare(right),
  );
  const changed: Array<string> = [];
  const missing: Array<string> = [];

  for (const relativePath of expectedFiles) {
    try {
      const actual = await fs.readFile(path.join(root, relativePath), "utf8");
      if (actual !== rendered.get(relativePath)) changed.push(relativePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        missing.push(relativePath);
        continue;
      }
      throw error;
    }
  }

  const actualFiles = await listFiles(path.join(root, generatedDirectory));
  const expected = new Set(expectedFiles);
  const unexpected = actualFiles
    .map((file) => normalizeOxlintArtifactPath(path.relative(root, file)))
    .filter((file) => !expected.has(file))
    .toSorted((left, right) => left.localeCompare(right));

  return { changed, missing, unexpected };
}

export async function writeOxlintArtifacts(
  root: string,
  rendered: RenderedArtifacts,
): Promise<void> {
  const diff = await diffOxlintArtifacts(root, rendered);
  await Promise.all(
    diff.unexpected.map((relativePath) =>
      fs.rm(path.join(root, relativePath), { force: true }),
    ),
  );

  for (const [relativePath, contents] of rendered) {
    const filePath = path.join(root, relativePath);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, contents);
  }
}

export function hasOxlintArtifactDiff(diff: OxlintArtifactDiff): boolean {
  return (
    diff.changed.length > 0 ||
    diff.missing.length > 0 ||
    diff.unexpected.length > 0
  );
}

export function formatOxlintArtifactDiff(diff: OxlintArtifactDiff): string {
  const lines = ["Generated Oxlint artifacts are out of date."];
  for (const file of diff.changed) lines.push(`  changed: ${file}`);
  for (const file of diff.missing) lines.push(`  missing: ${file}`);
  for (const file of diff.unexpected) lines.push(`  unexpected: ${file}`);
  lines.push("Run `pnpm generate:oxlint` and commit the result.");
  return lines.join("\n");
}
