[
  {
    "name": "[ignored]",
  },
  {
    "name": "[ignored]",
  },
  {
    "name": "[ignored]",
  },
  {
    "name": "antfu/javascript/rules",
    "plugins": [
      "antfu",
      "unused-imports",
      "github",
    ],
    "rules": [
      "accessor-pairs",
      "antfu/no-top-level-await",
      "array-callback-return",
      "block-scoped-var",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "func-style",
      "max-params",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-async-promise-executor",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-console",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-implicit-coercion",
      "no-implied-eval",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-obj-calls",
      "no-octal",
      "no-octal-escape",
      "- no-param-reassign",
      "no-proto",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unused-expressions",
      "no-unused-vars",
      "no-use-before-define",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "one-var",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-destructuring",
      "prefer-exponentiation-operator",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "sort-imports",
      "symbol-description",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "use-isnan",
      "valid-typeof",
      "vars-on-top",
      "yoda",
      "github/array-foreach",
      "github/async-currenttarget",
      "github/async-preventdefault",
      "github/get-attribute",
      "github/no-blur",
      "github/no-implicit-buggy-globals",
      "github/no-inner-html",
      "github/no-innerText",
      "github/no-dynamic-script-tag",
      "github/no-useless-passive",
      "github/prefer-observers",
      "github/require-passive-events",
      "github/unescaped-html-literal",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/javascript/disables/cli",
    "rules": [
      "- no-console",
    ],
  },
  {
    "files": [
      ".prettierrc.mjs",
    ],
    "name": "nirtamir2/javascript/prettier-overrides",
    "rules": [
      "- github/unescaped-html-literal",
    ],
  },
  {
    "name": "nirtamir2/javascript/typescript-compat",
    "rules": [
      "- dot-notation",
    ],
  },
  {
    "name": "array-func/recommended",
    "plugins": [
      "array-func",
    ],
    "rules": [
      "array-func/from-map",
      "array-func/no-unnecessary-this-arg",
      "array-func/prefer-array-from",
      "array-func/avoid-reverse",
    ],
  },
  {
    "name": "nirtamir2/javascript/arrayFunc/overrides",
    "rules": [
      "- array-func/prefer-array-from",
    ],
  },
  {
    "plugins": [
      "optimize-regex",
    ],
    "rules": [
      "optimize-regex/optimize-regex",
    ],
  },
  {
    "name": "nirtamir2/javascript/workspaces",
    "plugins": [
      "workspaces",
    ],
    "rules": [
      "workspaces/no-relative-imports",
      "workspaces/no-absolute-imports",
      "workspaces/require-dependency",
    ],
  },
  {
    "name": "no-use-extend-native/recommended",
    "plugins": [
      "no-use-extend-native",
    ],
    "rules": [
      "no-use-extend-native/no-use-extend-native",
    ],
  },
  {
    "name": "sonarjs/recommended",
    "plugins": [
      "sonarjs",
    ],
    "rules": [
      "- sonarjs/function-name",
      "sonarjs/class-name",
      "- sonarjs/max-lines",
      "- sonarjs/no-tab",
      "- sonarjs/variable-name",
      "- sonarjs/comment-regex",
      "sonarjs/no-commented-code",
      "- sonarjs/elseif-without-else",
      "sonarjs/no-fallthrough",
      "- sonarjs/nested-control-flow",
      "- sonarjs/too-many-break-or-continue-in-loop",
      "- sonarjs/max-lines-per-function",
      "- sonarjs/no-nested-incdec",
      "sonarjs/no-equals-in-for-termination",
      "sonarjs/no-extra-arguments",
      "- sonarjs/no-collapsible-if",
      "- sonarjs/expression-complexity",
      "- sonarjs/no-redundant-parentheses",
      "sonarjs/no-labels",
      "sonarjs/no-nested-assignment",
      "sonarjs/no-redundant-boolean",
      "sonarjs/prefer-single-boolean-return",
      "sonarjs/unused-import",
      "sonarjs/fixme-tag",
      "sonarjs/todo-tag",
      "- sonarjs/useless-string-operation",
      "- sonarjs/no-unused-function-argument",
      "- sonarjs/no-duplicate-string",
      "sonarjs/no-case-label-in-switch",
      "sonarjs/no-parameter-reassignment",
      "sonarjs/prefer-while",
      "- sonarjs/no-sonar-comments",
      "sonarjs/no-small-switch",
      "sonarjs/no-hardcoded-ip",
      "sonarjs/label-position",
      "sonarjs/public-static-readonly",
      "- sonarjs/file-header",
      "sonarjs/call-argument-line",
      "sonarjs/max-switch-cases",
      "sonarjs/no-unused-vars",
      "- sonarjs/prefer-immediate-return",
      "sonarjs/function-inside-loop",
      "sonarjs/code-eval",
      "- sonarjs/no-variable-usage-before-declaration",
      "sonarjs/future-reserved-words",
      "- sonarjs/array-constructor",
      "sonarjs/bitwise-operators",
      "- sonarjs/no-function-declaration-in-block",
      "sonarjs/no-primitive-wrappers",
      "- sonarjs/for-in",
      "- sonarjs/cyclomatic-complexity",
      "sonarjs/no-skipped-tests",
      "sonarjs/no-identical-expressions",
      "- sonarjs/no-nested-switch",
      "sonarjs/constructor-for-side-effects",
      "sonarjs/no-dead-store",
      "sonarjs/no-identical-conditions",
      "sonarjs/no-duplicated-branches",
      "sonarjs/deprecation",
      "sonarjs/no-inverted-boolean-check",
      "sonarjs/misplaced-loop-counter",
      "sonarjs/no-nested-functions",
      "sonarjs/no-hardcoded-passwords",
      "sonarjs/sql-queries",
      "sonarjs/insecure-cookie",
      "sonarjs/no-useless-increment",
      "sonarjs/no-globals-shadowing",
      "- sonarjs/no-undefined-assignment",
      "sonarjs/no-empty-test-file",
      "sonarjs/no-ignored-return",
      "- sonarjs/no-wildcard-import",
      "sonarjs/arguments-order",
      "sonarjs/pseudo-random",
      "sonarjs/for-loop-increment-sign",
      "- sonarjs/cookies",
      "sonarjs/null-dereference",
      "sonarjs/no-selector-parameter",
      "sonarjs/updated-loop-counter",
      "sonarjs/block-scoped-var",
      "- sonarjs/no-built-in-override",
      "- sonarjs/prefer-object-literal",
      "sonarjs/no-ignored-exceptions",
      "sonarjs/no-gratuitous-expressions",
      "sonarjs/file-uploads",
      "sonarjs/file-permissions",
      "sonarjs/no-empty-character-class",
      "sonarjs/no-unenclosed-multiline-block",
      "sonarjs/index-of-compare-to-positive-number",
      "sonarjs/assertions-in-tests",
      "sonarjs/no-implicit-global",
      "sonarjs/no-useless-catch",
      "sonarjs/xml-parser-xxe",
      "sonarjs/non-existent-operator",
      "- sonarjs/web-sql-database",
      "sonarjs/post-message",
      "sonarjs/no-array-delete",
      "sonarjs/no-alphabetical-sort",
      "sonarjs/no-incomplete-assertions",
      "sonarjs/no-global-this",
      "sonarjs/new-operator-misuse",
      "sonarjs/no-delete-var",
      "- sonarjs/strings-comparison",
      "- sonarjs/file-name-differ-from-class",
      "sonarjs/cookie-no-httponly",
      "sonarjs/no-nested-conditional",
      "- sonarjs/no-incorrect-string-concat",
      "sonarjs/different-types-comparison",
      "sonarjs/inverted-assertion-arguments",
      "- sonarjs/shorthand-property-grouping",
      "sonarjs/updated-const-var",
      "- sonarjs/arguments-usage",
      "- sonarjs/destructuring-assignment-syntax",
      "sonarjs/no-invariant-returns",
      "- sonarjs/arrow-function-convention",
      "- sonarjs/class-prototype",
      "sonarjs/generator-without-yield",
      "- sonarjs/no-require-or-define",
      "sonarjs/no-associative-arrays",
      "sonarjs/comma-or-logical-or-case",
      "sonarjs/no-redundant-jump",
      "sonarjs/inconsistent-function-call",
      "sonarjs/no-use-of-empty-return-value",
      "sonarjs/void-use",
      "- sonarjs/operation-returning-nan",
      "- sonarjs/values-not-convertible-to-numbers",
      "- sonarjs/non-number-in-arithmetic-expression",
      "sonarjs/cognitive-complexity",
      "sonarjs/argument-type",
      "sonarjs/in-operator-type-error",
      "sonarjs/array-callback-without-return",
      "- sonarjs/declarations-in-global-scope",
      "sonarjs/function-return-type",
      "- sonarjs/no-inconsistent-returns",
      "- sonarjs/no-reference-error",
      "sonarjs/no-all-duplicated-branches",
      "sonarjs/no-same-line-conditional",
      "- sonarjs/conditional-indentation",
      "sonarjs/no-collection-size-mischeck",
      "sonarjs/no-unthrown-error",
      "sonarjs/no-unused-collection",
      "sonarjs/no-os-command-from-path",
      "sonarjs/no-misleading-array-reverse",
      "- sonarjs/no-for-in-iterable",
      "sonarjs/no-element-overwrite",
      "sonarjs/no-identical-functions",
      "sonarjs/no-empty-collection",
      "sonarjs/no-redundant-assignments",
      "sonarjs/prefer-type-guard",
      "sonarjs/use-type-alias",
      "- sonarjs/no-return-type-any",
      "- sonarjs/no-implicit-dependencies",
      "sonarjs/no-useless-intersection",
      "sonarjs/weak-ssl",
      "sonarjs/no-weak-keys",
      "sonarjs/csrf",
      "sonarjs/production-debug",
      "sonarjs/prefer-default-last",
      "sonarjs/no-in-misuse",
      "sonarjs/no-duplicate-in-composite",
      "- sonarjs/max-union-size",
      "sonarjs/no-undefined-argument",
      "sonarjs/no-nested-template-literals",
      "sonarjs/prefer-promise-shorthand",
      "sonarjs/os-command",
      "sonarjs/no-redundant-optional",
      "- sonarjs/regular-expr",
      "- sonarjs/encryption",
      "sonarjs/hashing",
      "- sonarjs/bool-param-default",
      "- sonarjs/xpath",
      "- sonarjs/sockets",
      "sonarjs/no-try-promise",
      "- sonarjs/process-argv",
      "- sonarjs/standard-input",
      "sonarjs/unverified-certificate",
      "sonarjs/no-unsafe-unzip",
      "sonarjs/cors",
      "sonarjs/link-with-target-blank",
      "sonarjs/disabled-auto-escaping",
      "sonarjs/table-header",
      "sonarjs/no-table-as-layout",
      "sonarjs/table-header-reference",
      "sonarjs/object-alt-content",
      "sonarjs/no-clear-text-protocols",
      "sonarjs/publicly-writable-directories",
      "sonarjs/unverified-hostname",
      "sonarjs/encryption-secure-mode",
      "sonarjs/no-weak-cipher",
      "sonarjs/no-intrusive-permissions",
      "sonarjs/insecure-jwt-token",
      "sonarjs/x-powered-by",
      "sonarjs/hidden-files",
      "sonarjs/content-length",
      "sonarjs/disabled-resource-integrity",
      "sonarjs/content-security-policy",
      "sonarjs/no-mixed-content",
      "sonarjs/frame-ancestors",
      "sonarjs/no-mime-sniff",
      "sonarjs/no-referrer-policy",
      "sonarjs/strict-transport-security",
      "- sonarjs/certificate-transparency",
      "- sonarjs/dns-prefetching",
      "sonarjs/confidential-information-logging",
      "sonarjs/no-ip-forward",
      "sonarjs/empty-string-repetition",
      "sonarjs/regex-complexity",
      "sonarjs/anchor-precedence",
      "sonarjs/slow-regex",
      "sonarjs/no-invalid-regexp",
      "sonarjs/unused-named-groups",
      "sonarjs/no-same-argument-assert",
      "- sonarjs/unicode-aware-regex",
      "sonarjs/no-misleading-character-class",
      "sonarjs/duplicates-in-character-class",
      "sonarjs/session-regeneration",
      "sonarjs/test-check-exception",
      "sonarjs/stable-tests",
      "sonarjs/no-empty-after-reluctant",
      "sonarjs/single-character-alternation",
      "sonarjs/no-code-after-done",
      "sonarjs/disabled-timeout",
      "sonarjs/chai-determinate-assertion",
      "- sonarjs/aws-s3-bucket-server-encryption",
      "sonarjs/aws-s3-bucket-insecure-http",
      "sonarjs/aws-s3-bucket-versioning",
      "sonarjs/aws-s3-bucket-granted-access",
      "sonarjs/no-angular-bypass-sanitization",
      "sonarjs/aws-iam-public-access",
      "sonarjs/aws-ec2-unencrypted-ebs-volume",
      "sonarjs/aws-s3-bucket-public-access",
      "- sonarjs/no-vue-bypass-sanitization",
      "sonarjs/aws-iam-all-privileges",
      "sonarjs/aws-rds-unencrypted-databases",
      "- sonarjs/aws-iam-all-resources-accessible",
      "sonarjs/aws-opensearchservice-domain",
      "sonarjs/aws-iam-privilege-escalation",
      "sonarjs/aws-sagemaker-unencrypted-notebook",
      "sonarjs/aws-restricted-ip-admin-access",
      "sonarjs/no-empty-alternatives",
      "sonarjs/no-control-regex",
      "sonarjs/no-regex-spaces",
      "sonarjs/aws-sns-unencrypted-topics",
      "sonarjs/existing-groups",
      "sonarjs/aws-ec2-rds-dms-public",
      "sonarjs/aws-sqs-unencrypted-queue",
      "sonarjs/no-empty-group",
      "sonarjs/aws-efs-unencrypted",
      "sonarjs/aws-apigateway-public-api",
      "sonarjs/stateful-regex",
      "sonarjs/concise-regex",
      "sonarjs/single-char-in-character-classes",
      "sonarjs/no-hardcoded-secrets",
      "sonarjs/no-exclusive-tests",
      "sonarjs/hardcoded-secret-signatures",
      "sonarjs/jsx-no-leaked-render",
      "sonarjs/no-hook-setter-in-body",
      "sonarjs/no-useless-react-setstate",
      "sonarjs/no-uniq-key",
      "sonarjs/redundant-type-aliases",
      "sonarjs/prefer-regexp-exec",
      "sonarjs/no-internal-api-use",
      "sonarjs/prefer-read-only-props",
      "sonarjs/no-literal-call",
      "sonarjs/reduce-initial-value",
      "sonarjs/no-async-constructor",
      "sonarjs/review-blockchain-mnemonic",
      "sonarjs/dynamically-constructed-templates",
      "sonarjs/no-session-cookies-on-static-assets",
    ],
    "settings": {
      "react": {
        "version": "999.999.999",
      },
    },
  },
  {
    "name": "nirtamir2/javascript/sonar/disables",
    "rules": [
      "- sonarjs/prefer-read-only-props",
      "- sonarjs/deprecation",
      "- sonarjs/new-cap",
      "- sonarjs/todo-tag",
      "- sonarjs/no-fallthrough",
      "- sonarjs/void-use",
    ],
  },
  {
    "plugins": [
      "clsx",
    ],
    "rules": [
      "clsx/forbid-array-expressions",
      "clsx/forbid-false-inside-object-expressions",
      "clsx/forbid-true-inside-object-expressions",
      "clsx/no-redundant-clsx",
      "clsx/no-spreading",
      "clsx/prefer-merged-neighboring-elements",
    ],
  },
  {
    "name": "antfu/eslint-comments/rules",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "- @eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "name": "antfu/node/rules",
    "plugins": [
      "n",
    ],
    "rules": [
      "n/handle-callback-err",
      "n/no-deprecated-api",
      "n/no-exports-assign",
      "n/no-new-require",
      "n/no-path-concat",
      "n/prefer-global/buffer",
      "n/prefer-global/process",
      "n/process-exit-as-throw",
    ],
  },
  {
    "files": [
      "**/env.ts",
    ],
    "name": "nirtamir2/node/t3-env",
    "rules": [
      "- n/prefer-global/process",
    ],
  },
  {
    "name": "antfu/imports/rules",
    "plugins": [
      "antfu",
      "import-x",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import-x/consistent-type-specifier-style",
      "import-x/first",
      "import-x/no-duplicates",
      "import-x/no-mutable-exports",
      "import-x/no-named-default",
      "import-x/no-self-import",
      "import-x/no-webpack-loader-syntax",
      "- import-x/order",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/imports/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "name": "nirtamir2/unicorn/rules",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "- no-negated-condition",
      "- no-nested-ternary",
      "- unicorn/better-regex",
      "unicorn/catch-error-name",
      "unicorn/consistent-assert",
      "unicorn/consistent-date-clone",
      "unicorn/consistent-destructuring",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-existence-index-check",
      "unicorn/consistent-function-scoping",
      "unicorn/consistent-template-literal-escape",
      "- unicorn/custom-error-definition",
      "unicorn/empty-brace-spaces",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/expiring-todo-comments",
      "unicorn/explicit-length-check",
      "- unicorn/filename-case",
      "unicorn/import-style",
      "unicorn/isolated-functions",
      "unicorn/new-for-builtins",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-accessor-recursion",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-callback-reference",
      "unicorn/no-array-for-each",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-array-reduce",
      "unicorn/no-array-reverse",
      "unicorn/no-array-sort",
      "unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-console-spaces",
      "unicorn/no-document-cookie",
      "unicorn/no-empty-file",
      "unicorn/no-for-loop",
      "unicorn/no-hex-escape",
      "unicorn/no-immediate-mutation",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-fetch-options",
      "unicorn/no-invalid-remove-event-listener",
      "- unicorn/no-keyword-prefix",
      "unicorn/no-lonely-if",
      "unicorn/no-magic-array-flat-depth",
      "unicorn/no-named-default",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-nested-ternary",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "- unicorn/no-null",
      "unicorn/no-object-as-default-parameter",
      "unicorn/no-process-exit",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "unicorn/no-typeof-undefined",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-array-splice-count",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-polyfills",
      "unicorn/no-unnecessary-slice-end",
      "unicorn/no-unreadable-array-destructuring",
      "unicorn/no-unreadable-iife",
      "- unicorn/no-unused-properties",
      "unicorn/no-useless-collection-argument",
      "unicorn/no-useless-error-capture-stack-trace",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-iterator-to-array",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-spread",
      "unicorn/no-useless-switch-case",
      "unicorn/no-useless-undefined",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "- unicorn/numeric-separators-style",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-flat-map",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-bigint-literals",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-class-fields",
      "unicorn/prefer-classlist-toggle",
      "unicorn/prefer-code-point",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-dataset",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-event-target",
      "unicorn/prefer-export-from",
      "unicorn/prefer-global-this",
      "- unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "- unicorn/prefer-json-parse-buffer",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-math-min-max",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-prototype-methods",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-reflect-apply",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-response-static-json",
      "unicorn/prefer-set-has",
      "unicorn/prefer-set-size",
      "unicorn/prefer-simple-condition-first",
      "unicorn/prefer-single-call",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-raw",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-string-trim-start-end",
      "unicorn/prefer-structured-clone",
      "unicorn/prefer-switch",
      "unicorn/prefer-ternary",
      "unicorn/prefer-top-level-await",
      "unicorn/prefer-type-error",
      "- unicorn/prevent-abbreviations",
      "unicorn/relative-url-style",
      "unicorn/require-array-join-separator",
      "unicorn/require-module-attributes",
      "unicorn/require-module-specifiers",
      "unicorn/require-number-to-fixed-digits-argument",
      "- unicorn/require-post-message-target-origin",
      "- unicorn/string-content",
      "unicorn/switch-case-braces",
      "unicorn/switch-case-break-position",
      "unicorn/template-indent",
      "unicorn/text-encoding-identifier-case",
      "unicorn/throw-new-error",
    ],
  },
  {
    "name": "antfu/command/rules",
    "plugins": [
      "command",
    ],
    "rules": [
      "command/command",
    ],
  },
  {
    "name": "antfu/perfectionist/setup",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-exports",
      "perfectionist/sort-imports",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "antfu/jsx/setup",
    "plugins": [
      "jsx-a11y",
      "@stylistic",
    ],
    "rules": [
      "jsx-a11y/alt-text",
      "- jsx-a11y/anchor-ambiguous-text",
      "jsx-a11y/anchor-has-content",
      "jsx-a11y/anchor-is-valid",
      "jsx-a11y/aria-activedescendant-has-tabindex",
      "jsx-a11y/aria-props",
      "jsx-a11y/aria-proptypes",
      "jsx-a11y/aria-role",
      "jsx-a11y/aria-unsupported-elements",
      "jsx-a11y/autocomplete-valid",
      "jsx-a11y/click-events-have-key-events",
      "jsx-a11y/control-has-associated-label",
      "jsx-a11y/heading-has-content",
      "jsx-a11y/html-has-lang",
      "jsx-a11y/iframe-has-title",
      "jsx-a11y/img-redundant-alt",
      "jsx-a11y/interactive-supports-focus",
      "jsx-a11y/label-has-associated-control",
      "- jsx-a11y/label-has-for",
      "jsx-a11y/media-has-caption",
      "jsx-a11y/mouse-events-have-key-events",
      "jsx-a11y/no-access-key",
      "jsx-a11y/no-autofocus",
      "jsx-a11y/no-distracting-elements",
      "jsx-a11y/no-interactive-element-to-noninteractive-role",
      "jsx-a11y/no-noninteractive-element-interactions",
      "jsx-a11y/no-noninteractive-element-to-interactive-role",
      "jsx-a11y/no-noninteractive-tabindex",
      "jsx-a11y/no-redundant-roles",
      "jsx-a11y/no-static-element-interactions",
      "jsx-a11y/role-has-required-aria-props",
      "jsx-a11y/role-supports-aria-props",
      "jsx-a11y/scope",
      "jsx-a11y/tabindex-no-positive",
      "@stylistic/jsx-quotes",
      "@stylistic/jsx-self-closing-comp",
    ],
  },
  {
    "name": "antfu/typescript/setup",
    "plugins": [
      "antfu",
      "@typescript-eslint",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "extraFileExtensions": [
          ".vue",
        ],
        "sourceType": "module",
      },
    },
    "name": "antfu/typescript/parser",
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "name": "antfu/typescript/rules",
    "rules": [
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-duplicate-enum-values",
      "- @typescript-eslint/no-dynamic-delete",
      "@typescript-eslint/no-empty-object-type",
      "- @typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "- @typescript-eslint/no-extraneous-class",
      "- @typescript-eslint/no-invalid-void-type",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "- @typescript-eslint/no-non-null-assertion",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-function-type",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "- @typescript-eslint/no-unused-vars",
      "- no-useless-constructor",
      "- @typescript-eslint/no-useless-constructor",
      "@typescript-eslint/no-wrapper-object-types",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-literal-enum-member",
      "@typescript-eslint/prefer-namespace-keyword",
      "- @typescript-eslint/triple-slash-reference",
      "- @typescript-eslint/unified-signatures",
      "- no-dupe-class-members",
      "- no-redeclare",
      "- no-use-before-define",
      "@typescript-eslint/consistent-type-definitions",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/method-signature-style",
      "@typescript-eslint/no-dupe-class-members",
      "@typescript-eslint/no-redeclare",
      "@typescript-eslint/no-use-before-define",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "antfu/typescript/disables/dts",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- import-x/no-duplicates",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "name": "antfu/typescript/erasable-syntax-only",
    "plugins": [
      "erasable-syntax-only",
    ],
    "rules": [
      "erasable-syntax-only/enums",
      "erasable-syntax-only/import-aliases",
      "erasable-syntax-only/namespaces",
      "erasable-syntax-only/parameter-properties",
    ],
  },
  {
    "files": [
      "**/*.{test,spec}.ts?(x)",
    ],
    "name": "antfu/typescript/disables/test",
    "rules": [
      "- no-unused-expressions",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "antfu/typescript/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {},
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "ignores": [
      "**/*.md/**",
      "**/*.astro/*.ts",
    ],
    "name": "nirtamir2/typescript-rules",
    "rules": [
      "- no-undef",
      "- no-magic-numbers",
      "- @typescript-eslint/no-magic-numbers",
      "- no-shadow",
      "- @typescript-eslint/no-shadow",
      "- @typescript-eslint/class-methods-use-this",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/explicit-module-boundary-types",
      "- @typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/prefer-readonly",
      "- @typescript-eslint/prefer-readonly-parameter-types",
      "- @typescript-eslint/naming-convention",
      "- @typescript-eslint/ban-tslint-comment",
      "@typescript-eslint/no-unused-vars",
      "@typescript-eslint/consistent-generic-constructors",
      "@typescript-eslint/no-import-type-side-effects",
      "@typescript-eslint/no-useless-empty-export",
      "@typescript-eslint/ban-ts-comment",
      "@typescript-eslint/adjacent-overload-signatures",
      "@typescript-eslint/array-type",
      "@typescript-eslint/no-restricted-types",
      "@typescript-eslint/class-literal-property-style",
      "@typescript-eslint/consistent-indexed-object-style",
      "@typescript-eslint/consistent-type-assertions",
      "@typescript-eslint/consistent-type-imports",
      "- @typescript-eslint/consistent-type-exports",
      "- default-param-last",
      "@typescript-eslint/default-param-last",
      "- @typescript-eslint/dot-notation",
      "- @typescript-eslint/explicit-member-accessibility",
      "- init-declarations",
      "@typescript-eslint/init-declarations",
      "@typescript-eslint/member-ordering",
      "@typescript-eslint/method-signature-style",
      "@typescript-eslint/no-confusing-non-null-assertion",
      "- no-duplicate-imports",
      "- no-empty-function",
      "@typescript-eslint/no-empty-function",
      "@typescript-eslint/no-inferrable-types",
      "- no-invalid-this",
      "@typescript-eslint/no-invalid-this",
      "- no-loop-func",
      "@typescript-eslint/no-loop-func",
      "- no-loss-of-precision",
      "@typescript-eslint/parameter-properties",
      "@typescript-eslint/no-redeclare",
      "- no-restricted-imports",
      "@typescript-eslint/no-restricted-imports",
      "- @typescript-eslint/only-throw-error",
      "- @typescript-eslint/no-unnecessary-qualifier",
      "@typescript-eslint/no-use-before-define",
      "- @typescript-eslint/non-nullable-type-assertion-style",
      "@typescript-eslint/prefer-enum-initializers",
      "@typescript-eslint/prefer-for-of",
      "@typescript-eslint/prefer-function-type",
      "- @typescript-eslint/prefer-includes",
      "- @typescript-eslint/prefer-nullish-coalescing",
      "- @typescript-eslint/prefer-optional-chain",
      "- @typescript-eslint/prefer-regexp-exec",
      "- @typescript-eslint/prefer-string-starts-ends-with",
      "- @typescript-eslint/require-array-sort-compare",
      "- @typescript-eslint/return-await",
      "- array-callback-return",
      "- @typescript-eslint/await-thenable",
      "- @typescript-eslint/no-base-to-string",
      "- @typescript-eslint/no-confusing-void-expression",
      "@typescript-eslint/no-dynamic-delete",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extraneous-class",
      "- @typescript-eslint/no-floating-promises",
      "- @typescript-eslint/no-for-in-array",
      "- @typescript-eslint/no-implied-eval",
      "@typescript-eslint/no-invalid-void-type",
      "- @typescript-eslint/no-meaningless-void-operator",
      "- @typescript-eslint/no-misused-promises",
      "@typescript-eslint/no-non-null-assertion",
      "- @typescript-eslint/no-unnecessary-boolean-literal-compare",
      "- @typescript-eslint/no-unnecessary-condition",
      "- @typescript-eslint/no-unnecessary-type-arguments",
      "- @typescript-eslint/no-unnecessary-type-assertion",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "@typescript-eslint/no-useless-constructor",
      "- @typescript-eslint/prefer-reduce-type-parameter",
      "- @typescript-eslint/prefer-return-this-type",
      "- @typescript-eslint/promise-function-async",
      "- @typescript-eslint/require-await",
      "- @typescript-eslint/restrict-plus-operands",
      "- @typescript-eslint/restrict-template-expressions",
      "- @typescript-eslint/strict-boolean-expressions",
      "- @typescript-eslint/switch-exhaustiveness-check",
      "@typescript-eslint/triple-slash-reference",
      "- @typescript-eslint/unbound-method",
      "@typescript-eslint/unified-signatures",
      "- dot-notation",
      "- no-implied-eval",
      "- no-throw-literal",
      "- require-await",
      "- @typescript-eslint/consistent-return",
      "- @typescript-eslint/no-array-delete",
      "- @typescript-eslint/no-deprecated",
      "- @typescript-eslint/no-duplicate-type-constituents",
      "- @typescript-eslint/no-misused-spread",
      "- @typescript-eslint/no-mixed-enums",
      "- @typescript-eslint/no-redundant-type-constituents",
      "- @typescript-eslint/no-unnecessary-template-expression",
      "- @typescript-eslint/no-unnecessary-type-conversion",
      "- @typescript-eslint/no-unnecessary-type-parameters",
      "- @typescript-eslint/no-unsafe-enum-comparison",
      "- @typescript-eslint/no-unsafe-type-assertion",
      "- @typescript-eslint/no-unsafe-unary-minus",
      "- @typescript-eslint/no-useless-default-assignment",
      "- @typescript-eslint/prefer-destructuring",
      "- @typescript-eslint/prefer-find",
      "- @typescript-eslint/prefer-promise-reject-errors",
      "- @typescript-eslint/related-getter-setter-pairs",
      "- @typescript-eslint/strict-void-return",
      "- @typescript-eslint/use-unknown-in-catch-callback-variable",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "name": "nirtamir2/typescript/overrides",
  },
  {
    "name": "antfu/e18e/rules",
    "plugins": [
      "e18e",
    ],
    "rules": [
      "e18e/prefer-array-at",
      "e18e/prefer-array-fill",
      "e18e/prefer-includes",
      "e18e/prefer-array-to-reversed",
      "e18e/prefer-array-to-sorted",
      "e18e/prefer-array-to-spliced",
      "e18e/prefer-nullish-coalescing",
      "e18e/prefer-object-has-own",
      "e18e/prefer-spread-syntax",
      "e18e/prefer-url-canparse",
      "e18e/prefer-array-from-map",
      "e18e/prefer-timer-args",
      "e18e/prefer-date-now",
      "e18e/prefer-regex-test",
      "e18e/prefer-array-some",
      "e18e/prefer-static-regex",
    ],
  },
  {
    "name": "nirtamir2/regexp/rules",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "- no-empty-character-class",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "- regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "name": "antfu/vitest/setup",
    "plugins": [
      "vitest",
    ],
  },
  {
    "files": [
      "**/__tests__/**/*.?([cm])[jt]s?(x)",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/*.bench.?([cm])[jt]s?(x)",
      "**/*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/test/rules",
    "rules": [
      "- n/prefer-global/process",
      "vitest/consistent-test-it",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-only-tests",
      "vitest/prefer-hooks-in-order",
      "vitest/prefer-lowercase-title",
      "- antfu/no-top-level-await",
      "- no-unused-expressions",
      "- @typescript-eslint/explicit-function-return-type",
    ],
  },
  {
    "languageOptions": {},
    "name": "antfu/vue/setup",
    "plugins": [
      "vue",
    ],
  },
  {
    "files": [
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "vue-eslint-parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "extraFileExtensions": [
          ".vue",
        ],
        "sourceType": "module",
      },
    },
    "name": "antfu/vue/rules",
    "processor": "merged-processor:eslint-plugin-vue+eslint-processor-vue-blocks",
    "rules": [
      "vue/comment-directive",
      "vue/jsx-uses-vars",
      "- vue/multi-word-component-names",
      "vue/no-arrow-functions-in-watch",
      "vue/no-async-in-computed-properties",
      "vue/no-child-content",
      "vue/no-computed-properties-in-data",
      "vue/no-deprecated-data-object-declaration",
      "vue/no-deprecated-delete-set",
      "vue/no-deprecated-destroyed-lifecycle",
      "vue/no-deprecated-dollar-listeners-api",
      "vue/no-deprecated-dollar-scopedslots-api",
      "vue/no-deprecated-events-api",
      "vue/no-deprecated-filter",
      "vue/no-deprecated-functional-template",
      "vue/no-deprecated-html-element-is",
      "vue/no-deprecated-inline-template",
      "vue/no-deprecated-model-definition",
      "vue/no-deprecated-props-default-this",
      "vue/no-deprecated-router-link-tag-prop",
      "vue/no-deprecated-scope-attribute",
      "vue/no-deprecated-slot-attribute",
      "vue/no-deprecated-slot-scope-attribute",
      "vue/no-deprecated-v-bind-sync",
      "vue/no-deprecated-v-is",
      "vue/no-deprecated-v-on-native-modifier",
      "vue/no-deprecated-v-on-number-modifiers",
      "vue/no-deprecated-vue-config-keycodes",
      "- vue/no-dupe-keys",
      "vue/no-dupe-v-else-if",
      "vue/no-duplicate-attributes",
      "vue/no-export-in-script-setup",
      "vue/no-expose-after-await",
      "vue/no-lifecycle-after-await",
      "vue/no-mutating-props",
      "vue/no-parsing-error",
      "vue/no-ref-as-operand",
      "vue/no-reserved-component-names",
      "vue/no-reserved-keys",
      "vue/no-reserved-props",
      "vue/no-shared-component-data",
      "vue/no-side-effects-in-computed-properties",
      "vue/no-template-key",
      "vue/no-textarea-mustache",
      "vue/no-unused-components",
      "vue/no-unused-vars",
      "vue/no-use-computed-property-like-method",
      "vue/no-use-v-if-with-v-for",
      "vue/no-useless-template-attributes",
      "vue/no-v-for-template-key-on-child",
      "vue/no-v-text-v-html-on-component",
      "vue/no-watch-after-await",
      "vue/prefer-import-from-vue",
      "vue/require-component-is",
      "vue/require-prop-type-constructor",
      "vue/require-render-return",
      "vue/require-slots-as-functions",
      "vue/require-toggle-inside-transition",
      "vue/require-v-for-key",
      "vue/require-valid-default-prop",
      "vue/return-in-computed-property",
      "vue/return-in-emits-validator",
      "vue/use-v-on-exact",
      "vue/valid-attribute-name",
      "vue/valid-define-emits",
      "vue/valid-define-options",
      "vue/valid-define-props",
      "vue/valid-next-tick",
      "vue/valid-template-root",
      "vue/valid-v-bind",
      "vue/valid-v-cloak",
      "vue/valid-v-else-if",
      "vue/valid-v-else",
      "vue/valid-v-for",
      "vue/valid-v-html",
      "vue/valid-v-if",
      "vue/valid-v-is",
      "vue/valid-v-memo",
      "vue/valid-v-model",
      "vue/valid-v-on",
      "vue/valid-v-once",
      "vue/valid-v-pre",
      "vue/valid-v-show",
      "vue/valid-v-slot",
      "vue/valid-v-text",
      "vue/attribute-hyphenation",
      "vue/component-definition-name-casing",
      "vue/first-attribute-linebreak",
      "vue/html-closing-bracket-newline",
      "vue/html-closing-bracket-spacing",
      "vue/html-end-tags",
      "vue/html-indent",
      "vue/html-quotes",
      "vue/html-self-closing",
      "- vue/max-attributes-per-line",
      "vue/multiline-html-element-content-newline",
      "vue/mustache-interpolation-spacing",
      "vue/no-multi-spaces",
      "vue/no-spaces-around-equal-signs-in-attribute",
      "vue/no-template-shadow",
      "vue/one-component-per-file",
      "vue/prop-name-casing",
      "- vue/require-default-prop",
      "vue/require-explicit-emits",
      "- vue/require-prop-types",
      "vue/singleline-html-element-content-newline",
      "vue/v-bind-style",
      "vue/v-on-event-hyphenation",
      "vue/v-on-style",
      "vue/v-slot-style",
      "vue/attributes-order",
      "vue/block-order",
      "vue/no-lone-template",
      "vue/no-multiple-slot-args",
      "vue/no-required-prop-with-default",
      "- vue/no-v-html",
      "vue/order-in-components",
      "vue/this-in-template",
      "- antfu/no-top-level-await",
      "- n/prefer-global/process",
      "- @typescript-eslint/explicit-function-return-type",
      "vue/component-name-in-template-casing",
      "vue/component-options-name-casing",
      "- vue/component-tags-order",
      "vue/custom-event-name-casing",
      "vue/define-macros-order",
      "vue/dot-location",
      "vue/dot-notation",
      "vue/eqeqeq",
      "vue/no-empty-pattern",
      "vue/no-irregular-whitespace",
      "vue/no-loss-of-precision",
      "vue/no-restricted-syntax",
      "vue/no-restricted-v-bind",
      "- vue/no-setup-props-reactivity-loss",
      "vue/no-sparse-arrays",
      "vue/no-unused-refs",
      "vue/no-useless-v-bind",
      "vue/object-shorthand",
      "vue/prefer-separate-static-class",
      "vue/prefer-template",
      "vue/space-infix-ops",
      "vue/space-unary-ops",
    ],
  },
  {
    "name": "tailwindcss/setup",
    "plugins": [
      "better-tailwindcss",
    ],
  },
  {
    "name": "tailwindcss/settings",
    "settings": {
      "better-tailwindcss": {
        "entryPoint": "src/globals.css",
      },
    },
  },
  {
    "name": "tailwindcss/overrides",
    "rules": [
      "better-tailwindcss/enforce-consistent-class-order",
      "- better-tailwindcss/enforce-consistent-line-wrapping",
      "better-tailwindcss/no-deprecated-classes",
      "better-tailwindcss/no-duplicate-classes",
      "better-tailwindcss/no-unnecessary-whitespace",
      "better-tailwindcss/enforce-canonical-classes",
      "better-tailwindcss/no-conflicting-classes",
      "better-tailwindcss/no-unknown-classes",
    ],
  },
  {
    "name": "antfu/jsonc/setup",
    "plugins": [
      "jsonc",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "languageOptions": {
      "parser": "jsonc-eslint-parser",
    },
    "name": "antfu/jsonc/rules",
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-floating-decimal",
      "jsonc/no-hexadecimal-numeric-literals",
      "jsonc/no-infinity",
      "jsonc/no-multi-str",
      "jsonc/no-nan",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-octal",
      "jsonc/no-octal-escape",
      "jsonc/no-octal-numeric-literals",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "antfu/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/[jt]sconfig.json",
      "**/[jt]sconfig.*.json",
    ],
    "name": "antfu/sort/tsconfig-json",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "package.json",
      "**/package.json",
    ],
    "languageOptions": {
      "parser": "jsonc-eslint-parser",
    },
    "name": "antfu/pnpm/package-json",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/json-enforce-catalog",
      "pnpm/json-prefer-workspace-settings",
      "pnpm/json-valid-catalog",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "antfu/pnpm/pnpm-workspace-yaml",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/yaml-enforce-settings",
      "pnpm/yaml-no-duplicate-catalog-item",
      "pnpm/yaml-no-unused-catalog-item",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "antfu/pnpm/pnpm-workspace-yaml-sort",
    "plugins": [
      "yml",
    ],
    "rules": [
      "yml/sort-keys",
    ],
  },
  {
    "name": "eslint-plugin-default-import-name",
    "plugins": [
      "eslint-plugin-default-import-name",
    ],
    "rules": [
      "eslint-plugin-default-import-name/default-import-name",
    ],
  },
  {
    "name": "antfu/yml/setup",
    "plugins": [
      "yml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "antfu/yaml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "yml/block-mapping",
      "yml/block-sequence",
      "yml/no-empty-key",
      "yml/no-empty-sequence-entry",
      "yml/no-irregular-whitespace",
      "yml/plain-scalar",
      "yml/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "name": "antfu/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "antfu/toml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "name": "antfu/markdown/setup",
    "plugins": [
      "markdown",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "ignores": [
      "**/*.md/*.md",
    ],
    "name": "antfu/markdown/processor",
    "processor": "merged-processor:@eslint/markdown/markdown+pass-through",
  },
  {
    "files": [
      "**/*.md",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "antfu/markdown/parser",
  },
  {
    "files": [
      "**/*.md/**/*.?([cm])[jt]s?(x)",
      "**/*.md/**/*.vue",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "impliedStrict": true,
        },
      },
    },
    "name": "antfu/markdown/disables",
    "rules": [
      "- import-x/newline-after-import",
      "- no-alert",
      "- no-console",
      "- no-labels",
      "- no-lone-blocks",
      "- no-restricted-syntax",
      "- no-undef",
      "- no-unused-expressions",
      "- no-unused-labels",
      "- no-unused-vars",
      "- node/prefer-global/process",
      "- @stylistic/comma-dangle",
      "- @stylistic/eol-last",
      "- @typescript-eslint/consistent-type-imports",
      "- @typescript-eslint/no-namespace",
      "- @typescript-eslint/no-redeclare",
      "- @typescript-eslint/no-require-imports",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/no-use-before-define",
      "- @typescript-eslint/no-var-requires",
      "- unicode-bom",
      "- unused-imports/no-unused-imports",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "rules": [
      "- curly",
      "- no-unexpected-multiline",
      "- @stylistic/lines-around-comment",
      "- @stylistic/max-len",
      "- @stylistic/no-confusing-arrow",
      "- @stylistic/no-mixed-operators",
      "- @stylistic/no-tabs",
      "- @stylistic/quotes",
      "- @stylistic/js/lines-around-comment",
      "- @stylistic/js/max-len",
      "- @stylistic/js/no-confusing-arrow",
      "- @stylistic/js/no-mixed-operators",
      "- @stylistic/js/no-tabs",
      "- @stylistic/js/quotes",
      "- @stylistic/ts/lines-around-comment",
      "- @stylistic/ts/quotes",
      "- @typescript-eslint/lines-around-comment",
      "- @typescript-eslint/quotes",
      "- babel/quotes",
      "- unicorn/template-indent",
      "- vue/html-self-closing",
      "- vue/max-len",
      "- @babel/object-curly-spacing",
      "- @babel/semi",
      "- @stylistic/array-bracket-newline",
      "- @stylistic/array-bracket-spacing",
      "- @stylistic/array-element-newline",
      "- @stylistic/arrow-parens",
      "- @stylistic/arrow-spacing",
      "- @stylistic/block-spacing",
      "- @stylistic/brace-style",
      "- @stylistic/comma-dangle",
      "- @stylistic/comma-spacing",
      "- @stylistic/comma-style",
      "- @stylistic/computed-property-spacing",
      "- @stylistic/dot-location",
      "- @stylistic/eol-last",
      "- @stylistic/func-call-spacing",
      "- @stylistic/function-call-argument-newline",
      "- @stylistic/function-call-spacing",
      "- @stylistic/function-paren-newline",
      "- @stylistic/generator-star-spacing",
      "- @stylistic/implicit-arrow-linebreak",
      "- @stylistic/indent",
      "- @stylistic/jsx-quotes",
      "- @stylistic/key-spacing",
      "- @stylistic/keyword-spacing",
      "- @stylistic/linebreak-style",
      "- @stylistic/max-statements-per-line",
      "- @stylistic/multiline-ternary",
      "- @stylistic/new-parens",
      "- @stylistic/newline-per-chained-call",
      "- @stylistic/no-extra-parens",
      "- @stylistic/no-extra-semi",
      "- @stylistic/no-floating-decimal",
      "- @stylistic/no-mixed-spaces-and-tabs",
      "- @stylistic/no-multi-spaces",
      "- @stylistic/no-multiple-empty-lines",
      "- @stylistic/no-trailing-spaces",
      "- @stylistic/no-whitespace-before-property",
      "- @stylistic/nonblock-statement-body-position",
      "- @stylistic/object-curly-newline",
      "- @stylistic/object-curly-spacing",
      "- @stylistic/object-property-newline",
      "- @stylistic/one-var-declaration-per-line",
      "- @stylistic/operator-linebreak",
      "- @stylistic/padded-blocks",
      "- @stylistic/quote-props",
      "- @stylistic/rest-spread-spacing",
      "- @stylistic/semi",
      "- @stylistic/semi-spacing",
      "- @stylistic/semi-style",
      "- @stylistic/space-before-blocks",
      "- @stylistic/space-before-function-paren",
      "- @stylistic/space-in-parens",
      "- @stylistic/space-infix-ops",
      "- @stylistic/space-unary-ops",
      "- @stylistic/switch-colon-spacing",
      "- @stylistic/template-curly-spacing",
      "- @stylistic/template-tag-spacing",
      "- @stylistic/wrap-iife",
      "- @stylistic/wrap-regex",
      "- @stylistic/yield-star-spacing",
      "- @stylistic/member-delimiter-style",
      "- @stylistic/type-annotation-spacing",
      "- @stylistic/jsx-child-element-spacing",
      "- @stylistic/jsx-closing-bracket-location",
      "- @stylistic/jsx-closing-tag-location",
      "- @stylistic/jsx-curly-newline",
      "- @stylistic/jsx-curly-spacing",
      "- @stylistic/jsx-equals-spacing",
      "- @stylistic/jsx-first-prop-new-line",
      "- @stylistic/jsx-indent",
      "- @stylistic/jsx-indent-props",
      "- @stylistic/jsx-max-props-per-line",
      "- @stylistic/jsx-newline",
      "- @stylistic/jsx-one-expression-per-line",
      "- @stylistic/jsx-props-no-multi-spaces",
      "- @stylistic/jsx-tag-spacing",
      "- @stylistic/jsx-wrap-multilines",
      "- @stylistic/indent-binary-ops",
      "- @stylistic/type-generic-spacing",
      "- @stylistic/type-named-tuple-spacing",
      "- @stylistic/js/array-bracket-newline",
      "- @stylistic/js/array-bracket-spacing",
      "- @stylistic/js/array-element-newline",
      "- @stylistic/js/arrow-parens",
      "- @stylistic/js/arrow-spacing",
      "- @stylistic/js/block-spacing",
      "- @stylistic/js/brace-style",
      "- @stylistic/js/comma-dangle",
      "- @stylistic/js/comma-spacing",
      "- @stylistic/js/comma-style",
      "- @stylistic/js/computed-property-spacing",
      "- @stylistic/js/dot-location",
      "- @stylistic/js/eol-last",
      "- @stylistic/js/func-call-spacing",
      "- @stylistic/js/function-call-argument-newline",
      "- @stylistic/js/function-call-spacing",
      "- @stylistic/js/function-paren-newline",
      "- @stylistic/js/generator-star-spacing",
      "- @stylistic/js/implicit-arrow-linebreak",
      "- @stylistic/js/indent",
      "- @stylistic/js/jsx-quotes",
      "- @stylistic/js/key-spacing",
      "- @stylistic/js/keyword-spacing",
      "- @stylistic/js/linebreak-style",
      "- @stylistic/js/max-statements-per-line",
      "- @stylistic/js/multiline-ternary",
      "- @stylistic/js/new-parens",
      "- @stylistic/js/newline-per-chained-call",
      "- @stylistic/js/no-extra-parens",
      "- @stylistic/js/no-extra-semi",
      "- @stylistic/js/no-floating-decimal",
      "- @stylistic/js/no-mixed-spaces-and-tabs",
      "- @stylistic/js/no-multi-spaces",
      "- @stylistic/js/no-multiple-empty-lines",
      "- @stylistic/js/no-trailing-spaces",
      "- @stylistic/js/no-whitespace-before-property",
      "- @stylistic/js/nonblock-statement-body-position",
      "- @stylistic/js/object-curly-newline",
      "- @stylistic/js/object-curly-spacing",
      "- @stylistic/js/object-property-newline",
      "- @stylistic/js/one-var-declaration-per-line",
      "- @stylistic/js/operator-linebreak",
      "- @stylistic/js/padded-blocks",
      "- @stylistic/js/quote-props",
      "- @stylistic/js/rest-spread-spacing",
      "- @stylistic/js/semi",
      "- @stylistic/js/semi-spacing",
      "- @stylistic/js/semi-style",
      "- @stylistic/js/space-before-blocks",
      "- @stylistic/js/space-before-function-paren",
      "- @stylistic/js/space-in-parens",
      "- @stylistic/js/space-infix-ops",
      "- @stylistic/js/space-unary-ops",
      "- @stylistic/js/switch-colon-spacing",
      "- @stylistic/js/template-curly-spacing",
      "- @stylistic/js/template-tag-spacing",
      "- @stylistic/js/wrap-iife",
      "- @stylistic/js/wrap-regex",
      "- @stylistic/js/yield-star-spacing",
      "- @stylistic/ts/block-spacing",
      "- @stylistic/ts/brace-style",
      "- @stylistic/ts/comma-dangle",
      "- @stylistic/ts/comma-spacing",
      "- @stylistic/ts/func-call-spacing",
      "- @stylistic/ts/function-call-spacing",
      "- @stylistic/ts/indent",
      "- @stylistic/ts/key-spacing",
      "- @stylistic/ts/keyword-spacing",
      "- @stylistic/ts/member-delimiter-style",
      "- @stylistic/ts/no-extra-parens",
      "- @stylistic/ts/no-extra-semi",
      "- @stylistic/ts/object-curly-spacing",
      "- @stylistic/ts/semi",
      "- @stylistic/ts/space-before-blocks",
      "- @stylistic/ts/space-before-function-paren",
      "- @stylistic/ts/space-infix-ops",
      "- @stylistic/ts/type-annotation-spacing",
      "- @stylistic/jsx/jsx-child-element-spacing",
      "- @stylistic/jsx/jsx-closing-bracket-location",
      "- @stylistic/jsx/jsx-closing-tag-location",
      "- @stylistic/jsx/jsx-curly-newline",
      "- @stylistic/jsx/jsx-curly-spacing",
      "- @stylistic/jsx/jsx-equals-spacing",
      "- @stylistic/jsx/jsx-first-prop-new-line",
      "- @stylistic/jsx/jsx-indent",
      "- @stylistic/jsx/jsx-indent-props",
      "- @stylistic/jsx/jsx-max-props-per-line",
      "- @typescript-eslint/block-spacing",
      "- @typescript-eslint/brace-style",
      "- @typescript-eslint/comma-dangle",
      "- @typescript-eslint/comma-spacing",
      "- @typescript-eslint/func-call-spacing",
      "- @typescript-eslint/indent",
      "- @typescript-eslint/key-spacing",
      "- @typescript-eslint/keyword-spacing",
      "- @typescript-eslint/member-delimiter-style",
      "- @typescript-eslint/no-extra-parens",
      "- @typescript-eslint/no-extra-semi",
      "- @typescript-eslint/object-curly-spacing",
      "- @typescript-eslint/semi",
      "- @typescript-eslint/space-before-blocks",
      "- @typescript-eslint/space-before-function-paren",
      "- @typescript-eslint/space-infix-ops",
      "- @typescript-eslint/type-annotation-spacing",
      "- babel/object-curly-spacing",
      "- babel/semi",
      "- flowtype/boolean-style",
      "- flowtype/delimiter-dangle",
      "- flowtype/generic-spacing",
      "- flowtype/object-type-curly-spacing",
      "- flowtype/object-type-delimiter",
      "- flowtype/quotes",
      "- flowtype/semi",
      "- flowtype/space-after-type-colon",
      "- flowtype/space-before-generic-bracket",
      "- flowtype/space-before-type-colon",
      "- flowtype/union-intersection-spacing",
      "- react/jsx-child-element-spacing",
      "- react/jsx-closing-bracket-location",
      "- react/jsx-closing-tag-location",
      "- react/jsx-curly-newline",
      "- react/jsx-curly-spacing",
      "- react/jsx-equals-spacing",
      "- react/jsx-first-prop-new-line",
      "- react/jsx-indent",
      "- react/jsx-indent-props",
      "- react/jsx-max-props-per-line",
      "- react/jsx-newline",
      "- react/jsx-one-expression-per-line",
      "- react/jsx-props-no-multi-spaces",
      "- react/jsx-tag-spacing",
      "- react/jsx-wrap-multilines",
      "- standard/array-bracket-even-spacing",
      "- standard/computed-property-even-spacing",
      "- standard/object-curly-even-spacing",
      "- unicorn/empty-brace-spaces",
      "- unicorn/no-nested-ternary",
      "- unicorn/number-literal-case",
      "- vue/array-bracket-newline",
      "- vue/array-bracket-spacing",
      "- vue/array-element-newline",
      "- vue/arrow-spacing",
      "- vue/block-spacing",
      "- vue/block-tag-newline",
      "- vue/brace-style",
      "- vue/comma-dangle",
      "- vue/comma-spacing",
      "- vue/comma-style",
      "- vue/dot-location",
      "- vue/func-call-spacing",
      "- vue/html-closing-bracket-newline",
      "- vue/html-closing-bracket-spacing",
      "- vue/html-end-tags",
      "- vue/html-indent",
      "- vue/html-quotes",
      "- vue/key-spacing",
      "- vue/keyword-spacing",
      "- vue/max-attributes-per-line",
      "- vue/multiline-html-element-content-newline",
      "- vue/multiline-ternary",
      "- vue/mustache-interpolation-spacing",
      "- vue/no-extra-parens",
      "- vue/no-multi-spaces",
      "- vue/no-spaces-around-equal-signs-in-attribute",
      "- vue/object-curly-newline",
      "- vue/object-curly-spacing",
      "- vue/object-property-newline",
      "- vue/operator-linebreak",
      "- vue/quote-props",
      "- vue/script-indent",
      "- vue/singleline-html-element-content-newline",
      "- vue/space-in-parens",
      "- vue/space-infix-ops",
      "- vue/space-unary-ops",
      "- vue/template-curly-spacing",
      "- space-unary-word-ops",
      "- generator-star",
      "- no-comma-dangle",
      "- no-reserved-keys",
      "- no-space-before-semi",
      "- no-wrap-func",
      "- space-after-function-name",
      "- space-before-function-parentheses",
      "- space-in-brackets",
      "- no-arrow-condition",
      "- space-after-keywords",
      "- space-before-keywords",
      "- space-return-throw-case",
      "- no-spaced-func",
      "- indent-legacy",
      "- array-bracket-newline",
      "- array-bracket-spacing",
      "- array-element-newline",
      "- arrow-parens",
      "- arrow-spacing",
      "- block-spacing",
      "- brace-style",
      "- comma-dangle",
      "- comma-spacing",
      "- comma-style",
      "- computed-property-spacing",
      "- dot-location",
      "- eol-last",
      "- func-call-spacing",
      "- function-call-argument-newline",
      "- function-paren-newline",
      "- generator-star-spacing",
      "- implicit-arrow-linebreak",
      "- indent",
      "- jsx-quotes",
      "- key-spacing",
      "- keyword-spacing",
      "- linebreak-style",
      "- lines-around-comment",
      "- max-len",
      "- max-statements-per-line",
      "- multiline-ternary",
      "- new-parens",
      "- newline-per-chained-call",
      "- no-confusing-arrow",
      "- no-extra-parens",
      "- no-extra-semi",
      "- no-floating-decimal",
      "- no-mixed-operators",
      "- no-mixed-spaces-and-tabs",
      "- no-multi-spaces",
      "- no-multiple-empty-lines",
      "- no-tabs",
      "- no-trailing-spaces",
      "- no-whitespace-before-property",
      "- nonblock-statement-body-position",
      "- object-curly-newline",
      "- object-curly-spacing",
      "- object-property-newline",
      "- one-var-declaration-per-line",
      "- operator-linebreak",
      "- padded-blocks",
      "- quote-props",
      "- quotes",
      "- rest-spread-spacing",
      "- semi",
      "- semi-spacing",
      "- semi-style",
      "- space-before-blocks",
      "- space-before-function-paren",
      "- space-in-parens",
      "- space-infix-ops",
      "- space-unary-ops",
      "- switch-colon-spacing",
      "- template-curly-spacing",
      "- template-tag-spacing",
      "- wrap-iife",
      "- wrap-regex",
      "- yield-star-spacing",
      "- react/jsx-space-before-closing",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/disables/scripts",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- @typescript-eslint/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/disables/cli",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "antfu/disables/dts",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.{test,spec}.([tj])s?(x)",
    ],
    "name": "antfu/disables/test",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-unused-expressions",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "antfu/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "antfu/disables/config-files",
    "rules": [
      "- antfu/no-top-level-await",
      "- no-console",
      "- @typescript-eslint/explicit-function-return-type",
    ],
  },
]